### ISSUE TITLE
Tenant needs to be applied to clusters/vms to allow duplicate naming

### ISSUE THREAD

**Issue by nathan-sav** [bb-Ricardo/netbox-sync#10]
Netbox won't allow duplicate names with VMs if the tenant value is not set, even if the cluster is specified.

This is a problem even if you don't have dupe names, since vsphere 7.1 adds the new vcls vms that will always have naming conflicts:

2020-11-20 20:25:30,491 - ERROR: NetBox returned body: {'name': ['A virtual machine with this name already exists.']}
2020-11-20 20:25:30,491 - ERROR: Request Failed for virtual machine. Used data: {'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: phx'}], 'name': 'vCLS (2)', 'cluster': 5, 'role': 5, 'status': 'active', 'memory': 128, 'vcpus': 1, 'disk': 2, 'platform': 5, 'comments': "vSphere Cluster Services VM is deployed from an OVA with a minimal installed profile of PhotonOS. vSphere Cluster Services manage the resources, power state and availability of these VM's. vSphere Cluster Service VMs are required for maintaining the health and availability of vSphere Cluster Services. Any impact on the power state or resources of these VM's might degrade the health of the vSphere Cluster Services and cause vSphere DRS to cease operation for the cluster."}

I don't think it makes sense to auto-create a tenant based on the vsphere cluster name though, since in a business one tenant may have multiple clusters. I'd suggest adding a "tenant" option for each source inside settings.ini, so we can manually specify which tenant each clusters hosts/vms/everything get put into.

**Comment by bb-Ricardo** [comment]
So it's the same name and a different cluster and NetBox refuses the creation because the tenant is missing? Did I get this right?

**Comment by nathan-sav** [comment]
Yep, exactly. Even though they're in different clusters, if the tenant is not set then netbox will still flag it as a conflict. 

I had to dig through their github to figure out the rules around it, see: https://github.com/netbox-community/netbox/pull/3740

**Comment by bb-Ricardo** [comment]
That's truly helpful. I guess we have to add this option to allow for duplicate vm names.

Thank you so much.

**Comment by nathan-sav** [comment]
No, thank YOU for building this tool.

**Comment by nathan-sav** [comment]
Similarly, I think "site" should be set by the user in settings.ini rather than default to "Vcenter: name". A site contains physical assets like racks and circuits which may be shared with multiple vmware clusters.

**Comment by bb-Ricardo** [comment]
Just thinking of this again.

That means you would have to write a lot of regex to cover your VM names that will be assigned a tenant.

Or I just at it and then the user has to deal with the possible mess?

**Comment by nathan-sav** [comment]
For my particular use case, each cluster is dedicated to a tenant, so I wouldn't need any regexes. For most other people I think that a list of regex's might be acceptable, but hard to know what others use cases might be.

Alternatively to matching regexs on the VM name, how about mapping against tags in vmware? That would probably really simplify the regex's people have to write, since it could even just be a 1-to-1 mapping of tag -> tenant.

**Comment by bb-Ricardo** [comment]
Anyway, done.

Can you test it please?

**Comment by nathan-sav** [comment]
Thanks! Will do but might take me a couple days to circle back around to this.

**Comment by bb-Ricardo** [comment]
any chance you could test this?

**Comment by bb-Ricardo** [comment]
Due to no response in over a month I will close the ticket for now.
