### ISSUE TITLE
Error if nicOrder status is None

### ISSUE THREAD

**Issue by Profecy** [bb-Ricardo/netbox-sync#117]
Hi, I am doing a dry run against both my companies vcenters. However, at some point the script fails with the following error:

```
Traceback (most recent call last):
  File "./netbox-sync.py", line 145, in <module>
    main()
  File "./netbox-sync.py", line 121, in main
    source.apply()
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 492, in apply
    view_details.get("view_handler")(obj)
  File "/opt/netbox-sync/module/sources/vmware/connection.py", line 1480, in add_host
    if nic_order.activeNic is not None:
AttributeError: 'NoneType' object has no attribute 'activeNic'
```

What can I do ? Let me know if you need any more info.

**Comment by bb-Ricardo** [comment]
Hi,

which version of ESXi and vCenter are you running?

**Comment by bb-Ricardo** [comment]
Hey, can you try to checkout "development" branch and see if it works now?

Thant you.

**Comment by Profecy** [comment]
We use vCenter 7.0.3, 18778458 and ESXi 7.0.3, 18644231

I will try the development build as well. 
Thank you for the quick response!

**Comment by Profecy** [comment]
I have tried the development branch and it worked perfectly.
Thank you!

**Comment by bb-Ricardo** [comment]
great, then I will close this issue. Keep an eye out for new releases. So you can switch back to main once this fix is merged.

**Comment by bb-Ricardo** [comment]
If you like the project I would be happy about a :star:

**Comment by Profecy** [comment]
I will gladly ⭐ the project, it saves so much work!
