### ISSUE TITLE
Add Support to add WWN from Redfish import

### ISSUE THREAD

**Issue by schwos** [bb-Ricardo/netbox-sync#121]
So was running the netbox-sync tool with only redfish json files for now as the other issue is related to Virtual Machine imports and tag issues. You may or may not have run into storage fibre-channel cards installed within hosts with WWN. 

During the import they are listed as a NIC and have a MAC and WWN which has two additional hex numbers. This causes the import into Netbox to through errors as invalid MAC Address. It isn't wrong but also it isn't right.  I am bringing this up at the moment; but need to research further on how NetBox itself handles this..

-- Update -- --[https://github.com/netbox-community/netbox/pull/7986]-- 3.1.0 adds WWN support; currently on 3.0.9 may have to update netbox-sync to know WWN

> 2021-12-21 00:02:14,746 - ERROR: NetBox returned: PATCH /api/dcim/interfaces/395/ Bad Request
> 2021-12-21 00:02:14,746 - ERROR: NetBox returned body: {'mac_address': ['Invalid MAC address format: 20:00:00:00:C9:F8:03:CC']}
> 2021-12-21 00:02:14,747 - ERROR: Request Failed for interface. Used data: {'type': 'other', 'enabled': False, 'mac_address': '20:00:00:00:C9:F8:03:CC', 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-redfish-example'}]}
> 2021-12-21 00:02:14,747 - INFO: Updating NetBox 'interface' object 'Gig-E 3 (R730_CSXX482)' with data: {'type': 'other', 'enabled': False, 'mac_address': '20:00:00:00:C9:F8:03:CD', 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-redfish-example'}]}
> 2021-12-21 00:02:14,748 - DEBUG2: Sending PATCH to 'http://netbox.local:80/api/dcim/interfaces/396/' with data 'b'{"type": "other", "enabled": false, "mac_address": "20:00:00:00:C9:F8:03:CD", "tags": [{"name": "NetBox-synced"}, {"name": "Source: my-redfish-example"}]}''.
> 2021-12-21 00:02:14,810 - DEBUG2: Received HTTP Status 400.
> 2021-12-21 00:02:14,810 - ERROR: NetBox returned: PATCH /api/dcim/interfaces/396/ Bad Request
> 2021-12-21 00:02:14,810 - ERROR: NetBox returned body: {'mac_address': ['Invalid MAC address format: 20:00:00:00:C9:F8:03:CD']}
> 2021-12-21 00:02:14,810 - ERROR: Request Failed for interface. Used data: {'type': 'other', 'enabled': False, 'mac_address': '20:00:00:00:C9:F8:03:CD', 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-redfish-example'}]}
> 2021-12-21 00:02:14,811 - INFO: Updating NetBox 'interface' object 'Gig-E 2 (R730_CSXX482)' with data: {'type': 'other', 'enabled': False, 'mac_address': '20:00:00:00:C9:F8:04:EF', 'tags': [{'name': 'NetBox-synced'}, {'name': 'Source: my-redfish-example'}]}
> 2021-12-21 00:02:14,811 - DEBUG2: Sending PATCH to 'http://netbox.local:80/api/dcim/interfaces/390/' with data 'b'{"type": "other", "enabled": false, "mac_address": "20:00:00:00:C9:F8:04:EF", "tags": [{"name": "NetBox-synced"}, {"name": "Source: my-redfish-example"}]}''.
> 2021-12-21 00:02:14,874 - DEBUG2: Received HTTP Status 400.

**Comment by bb-Ricardo** [comment]
Yes, good point. The interface here https://demo.netbox.dev/api/docs/ shows that there is  a WWN attribute as well.

Will update the script. Thank you very much.

**Comment by bb-Ricardo** [comment]
I added a change for the WWN. Can you try out the branch 'add-support-for-interface-wwn' and see if it's working now?

Thank you

**Comment by schwos** [comment]
I can confirm that the WWN issue with Netbox 3.1.1 works; but found another possible issue which I will post separately for you.
