### ISSUE TITLE
IPMI/iLo/iDRAC Interface IP load

### ISSUE THREAD

**Issue by schwos** [bb-Ricardo/netbox-sync#122]
when loading the data for the hosts ipmi/iLo/idrac interface; it appears to put the ipmi/iLo/idrac interface FDQN/Hostname into the first nic not within it corresponding NIC. As well doesn't load the IP address when it furnished within the ipmi/iLO/idrac json under that associated nic. 

Trying to determine the order in which is loads MAC address's within the interface objects.

**Comment by schwos** [comment]
Update: So if we just set the overwrite the interface to true in the settings.ini file; it will self correct.; though you would think it grab the IP assigned to the NIC and place it within NETBOX? This possible?

**Comment by bb-Ricardo** [comment]
Hi, and sorry for not replying, very rude.

Are you using the check_redfish import?

I still don't really understand what is happening here. Can you describe the steps you take and some data examples? That would help a lot.

Thant you.

**Comment by schwos** [comment]
Sorry been busy recently.. Basically if we create systems within Netbox using the device template and has the interfaces created and you don't set overwrite interface to true it will load the idrac IP address into the first nic is finds regardless if it is a idrac or the first lom. So really I just set the script to true to overwrite as it will correct it based upon what it found within the inventory via the check_redfish import process.

**Comment by bb-Ricardo** [comment]
Sorry for this long no answer.

And how about having a system template without interfaces configured? Or does this not help?
