### ISSUE TITLE
Error creating custom fields

### ISSUE THREAD

**Issue by awbait** [bb-Ricardo/netbox-sync#125]
Found a bug with the creation of custom fields. Netbox does not create custom fields using dashes.

![image](https://user-images.githubusercontent.com/12417799/147601680-b1290e2f-2c1d-4311-8429-0567e4d076c8.png)

The error is probably right here:
https://github.com/bb-Ricardo/netbox-sync/blob/c26b726ba6659917fd73863f110add44141cd881/module/sources/vmware/connection.py#L820

**Comment by bb-Ricardo** [comment]
Hey,

Do you mean this one #123?

This is already fixed in development. Can you try it out please?

**Comment by awbait** [comment]
Hey. it seems to work in the development branch. Thx
