### ISSUE TITLE
Exclude standalone hosts as cluster

### ISSUE THREAD

**Issue by awbait** [bb-Ricardo/netbox-sync#126]
I have multiple clusters (icon with 3 PCs). I set the parameter cluster_include_filter = DAC and it works. However, I still have standalone hosts (one PC icon) that contain virtual machines. So I want to exclude them. Are they bypassing the exception check for now? and are created as a cluster. How can i do this?
I've tried adding like this:
host_exclude_filter = 172.18.36.12, 172.18.36.13, 172.18.36.216, 172.18.36.217, 192.168.245.48, esxi-vrn3.srv.local, esxi-vrn4.srv.local

![image](https://user-images.githubusercontent.com/12417799/147602083-98c3aa12-53a1-4f7a-ab16-c663db5df15d.png)
![image](https://user-images.githubusercontent.com/12417799/147602576-63cbe829-5bac-4b1d-8224-425a55f82793.png)

**Comment by bb-Ricardo** [comment]
Hey,

host_exclude_filter is an regex filter. try:
```
host_exclude_filter = 172.18.36.12|172.18.36.13|172.18.36.216|172.18.36.217|192.168.245.48|esxi-vrn3.srv.local|esxi-vrn4.srv.local
```

**Comment by awbait** [comment]
Hello. Yes fine. This filter has worked. Thank you.
