### ISSUE TITLE
Platform filter

### ISSUE THREAD

**Issue by awbait** [bb-Ricardo/netbox-sync#127]
Hey, how can platform filter be configured to 
.el7. = Centos 7
.el7uek. = Oracle Linux Server 7?

![image](https://user-images.githubusercontent.com/12417799/147647133-568490b9-804b-41a0-8868-65ff44c10b73.png)

**Comment by bb-Ricardo** [comment]
Hey, did you check the `vm_platform_relation`?

Be aware that the filter argument must also be a REGEX expression!!

**Comment by awbait** [comment]
> Hey, did you check the `vm_platform_relation`?
> 
> Be aware that the filter argument must also be a REGEX expression!!
I added
`.*el7.* = Centos7`
but it fails

**Comment by awbait** [comment]
Resolved.
.*\.el7\..* = Centos 7
