### ISSUE TITLE
Special characters in vcenter password can break operations

### ISSUE THREAD

**Issue by postilion** [bb-Ricardo/netbox-sync#128]
First things first: Love this package!  Netbox-sync just pulled in our entire VM infrastructure and saved us tons of time.  So Thank You!!

The one problem we encountered is that the first read-only vCenter credential we tried wouldn't work, due to a percent sign "%" in the password.  No amount of quoting or escaping seemed to work.  Not a big deal, we created a new credential with no percent signs, and got it up and running.  But might warrant a note in the instructions.

Thanks again!
-nic

**Comment by bb-Ricardo** [comment]
Thank you for the hint. Will try this out in my dev environment and see if it can be fixed.

**Comment by bb-Ricardo** [comment]
Hey, thanks again for this hint. I just disabled "interpolation" from config parser which is not used anyway.

I know you changed your password already but could you give the branch 'development' a try and see if it works now with a "%" in the password?

Thank you

**Comment by bb-Ricardo** [comment]
I assume this issue can be closed now.
