### ISSUE TITLE
VLAN using ESXi standard port groups

### ISSUE THREAD

**Issue by TomGrozev** [bb-Ricardo/netbox-sync#14]
Hi,

Great script, does everything perfectly except one thing, using ESXi standard port groups is not an option. Basically the VLANs and prefix assignments are setup in ESXi as standard port groups instead of using DistributedirtualPortGroups, hence the only VLAN that is create is the `ESXi Management Network (ID: 10)`. I have tried looking at the vSphere API in a way to modify the script to use standard port groups from ESXi but cannot seem to find a way. I'm new to the API so not too sure how to go about it.

Also because of not finding the prefixes in the VLANs, the VMs are not assigned to the correct prefixes as there are none imported. I know this can be done manually but with a large number of VMs it isnot feasibile to manually do this.

Is this a possible feature that could be added? I would do it myself if I knew how to query the API properly for the port groups & VLANs.

If you need more details please let me know.

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for testing it.

It could probably added but I actually don't know what you are talking about.

Can you add screenshots from a vCenter and point out the information you are missing?

Thank you.

**Comment by TomGrozev** [comment]
I'm not at work right now (where the vCenter is) but I will try to explain better. So the port groups and VLANs (along with the IP prefixes) are set on the host instead of being distributed through vCenter. I noticed that when adding the host in the script it does actually fetch the port groups but later filters them out and does not use them. I've had a look around at trying to edit the script but not too sure where VLANs are actually added in Netbox. I can see that they are eventually added in the inventory.py script but not sure the entire process. If you could point me to the right area I could most likely figure out a work around at least.

Since only the host's own VLAN is added to Netbox there are also no IP prefixes added and the IPs are just assigned without their groupings.

**Comment by bb-Ricardo** [comment]
Ah ok. So you want to add the host port groups to NetBox as well?

The program does that but only if the port is just tagged. If the program finds a "4095" VLAN then the port is configured as tagged all. If a port in Netbox is marked as "tagged-all" then you can't assign single tagged vlans. Only one untagged VLAN.

if you add a `print(pgroup)` to https://github.com/bb-Ricardo/netbox-sync/blob/main/module/sources/vmware/connection.py#L1368 you schould see the local port groups and their configuration.

Or paste them here and I can see if I missed something (very possible).

**Comment by TomGrozev** [comment]
Yes basically that is correct.

Unfortunately our server is having a bit of trouble today. Will have to try it later when it comes back online.

I want to be able to add these VLANs to netbox and have the VMs associated with the VLANs from the host. Is that something that is possible?

**Comment by bb-Ricardo** [comment]
The host port groups are only for NON VM Traffic VLANs.

Is this a host in a single/own cluster? It doesn't have distributed port groups?

**Comment by TomGrozev** [comment]
Correct, the port groups are set directly on the host in the vSwitch and there are no distributed port groups.

Here is the basic configuration (sorry for the redactions):
![vsphere port group setup](https://user-images.githubusercontent.com/1491414/100156186-987e9180-2efc-11eb-9f48-5e8b77233f78.PNG)

Here is an example of a port group outputted (also I assume you meant line 1387 in the connection file):

`2020-11-25 09:28:27,016 - DEBUG2: (vim.host.PortGroup) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 'key-vim.host.PortGroup-Core',
   port = (vim.host.PortGroup.Port) [
      (vim.host.PortGroup.Port) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'key-vim.host.PortGroup.Port-67108882',
         mac = (str) [
            '00:50:56:xx:xx:xx'
         ],
         type = 'virtualMachine'
      },
      (vim.host.PortGroup.Port) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'key-vim.host.PortGroup.Port-67108885',
         mac = (str) [
            '00:0c:29:xx:xx:xx'
         ],
         type = 'virtualMachine'
      },
      (vim.host.PortGroup.Port) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 'key-vim.host.PortGroup.Port-67108888',
         mac = (str) [
            '00:50:56:xx:xx:xx'
         ],
         type = 'virtualMachine'
      }
   ],
   vswitch = 'key-vim.host.VirtualSwitch-vSwitch0',
   computedPolicy = (vim.host.NetworkPolicy) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      security = (vim.host.NetworkPolicy.SecurityPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         allowPromiscuous = true,
         macChanges = true,
         forgedTransmits = true
      },
      nicTeaming = (vim.host.NetworkPolicy.NicTeamingPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         policy = 'loadbalance_srcid',
         reversePolicy = true,
         notifySwitches = true,
         rollingOrder = false,
         failureCriteria = (vim.host.NetworkPolicy.NicFailureCriteria) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            checkSpeed = 'minimum',
            speed = 10,
            checkDuplex = false,
            fullDuplex = false,
            checkErrorPercent = false,
            percentage = 0,
            checkBeacon = false
         },
         nicOrder = (vim.host.NetworkPolicy.NicOrderPolicy) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            activeNic = (str) [
               'vmnic0',
               'vmnic1'
            ],
            standbyNic = (str) []
         }
      },
      offloadPolicy = (vim.host.NetOffloadCapabilities) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         csumOffload = true,
         tcpSegmentation = true,
         zeroCopyXmit = true
      },
      shapingPolicy = (vim.host.NetworkPolicy.TrafficShapingPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         enabled = false,
         averageBandwidth = <unset>,
         peakBandwidth = <unset>,
         burstSize = <unset>
      }
   },
   spec = (vim.host.PortGroup.Specification) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      name = 'Alpha',
      vlanId = 40,
      vswitchName = 'vSwitch0',
      policy = (vim.host.NetworkPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         security = (vim.host.NetworkPolicy.SecurityPolicy) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            allowPromiscuous = <unset>,
            macChanges = <unset>,
            forgedTransmits = <unset>
         },
         nicTeaming = (vim.host.NetworkPolicy.NicTeamingPolicy) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            policy = <unset>,
            reversePolicy = <unset>,
            notifySwitches = <unset>,
            rollingOrder = <unset>,
            failureCriteria = (vim.host.NetworkPolicy.NicFailureCriteria) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               checkSpeed = <unset>,
               speed = <unset>,
               checkDuplex = <unset>,
               fullDuplex = <unset>,
               checkErrorPercent = <unset>,
               percentage = <unset>,
               checkBeacon = <unset>
            },
            nicOrder = <unset>
         },
         offloadPolicy = (vim.host.NetOffloadCapabilities) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            csumOffload = <unset>,
            tcpSegmentation = <unset>,
            zeroCopyXmit = <unset>
         },
         shapingPolicy = (vim.host.NetworkPolicy.TrafficShapingPolicy) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            enabled = <unset>,
            averageBandwidth = <unset>,
            peakBandwidth = <unset>,
            burstSize = <unset>
         }
      }
   }
}
`

**Comment by bb-Ricardo** [comment]
Let's see if I can match the VM MAC addresses to the host port group.

**Comment by TomGrozev** [comment]
I had a go at implementing this. It uses the port group names and seems a bit of a hacky solution. Can you take a look at it before I make a pull request?

https://github.com/TomGrozev/netbox-sync/tree/feature/use-host-portgroups

**Comment by bb-Ricardo** [comment]
I just fixed this one. Sorry I didn't use your solution.

can you try and see if this syncs prperly?

**Comment by TomGrozev** [comment]
Was hoping you would find a better solution, mine was quite hacky. Will test tomorrow.

**Comment by TomGrozev** [comment]
Works great, all VLANs are imported correctly. Thanks

Is there any possibility of getting the assigned prefixes or is that not possible with the API?

**Comment by bb-Ricardo** [comment]
That's great news, Thanks for testing.

>Is there any possibility of getting the assigned prefixes or is that not possible with the API?

I don't know what you're referring to. You can assign prefixes but the tool doesn't know which prefix might belong to a VLAN.
What's your idea?

**Comment by TomGrozev** [comment]
Don't worry about that one, all sorted.
