### ISSUE TITLE
Add support for proxy and client certificates (mTLS)

### ISSUE THREAD

**Issue by macEar** [bb-Ricardo/netbox-sync#140]
Hi there,

It'd be helpful if this tool supports proxies and client certificates (mTLS). As I can see it should be added somewhere here: https://github.com/bb-Ricardo/netbox-sync/blob/a9f25a630756f71f26ad845bc5d8dad86e355931/module/netbox/connection.py#L187

1. Add support for proxies:

```py
proxies = {
  'http': '...',
  'https': '...',
}
session.proxies.update(proxies)
```

2. Add support for client certificates (mTLS):

```py
cert = './xxx.pem'
privkey = '/./xxx.key'
session.cert = (cert, privkey)
```

**Comment by bb-Ricardo** [comment]
Hi, great idea.

This should be easily done. Will try to add this to the next release.

**Comment by bb-Ricardo** [comment]
Hey @macEar,

I added support for proxies to netbox-sync.

Can you test it out and see if it works for you?

**Comment by bb-Ricardo** [comment]
closing due to no response
