### ISSUE TITLE
advanced globs for regex matching?

### ISSUE THREAD

**Issue by pisaniej** [bb-Ricardo/netbox-sync#143]
Is it possible to match clusters to a site by multiple globs?

For example, here is a list of clusters:

* Team 1 ABC Cluster 1
* Team 1 ABC Cluster 2
* Team 2 ABC Cluster 1
* Team 1 XYZ Cluster 1
* Team 2 XYZ Cluster 1
* Team 2  XYZ Cluster 2

To the following sites:

* ABC Site
* XYZ Site

So, trying to use the following in `settings.ini`:

```
cluster_site_relation = *ABC* = ABC Site , *XYZ* = XYZ Site
```

Thanks

**Comment by bb-Ricardo** [comment]
Hi,

you could try this one:
```ini
cluster_site_relation = .*ABC.* = ABC Site , .*XYZ.* = XYZ Site
```

**Comment by pisaniej** [comment]
... that was it... thank you so much!
