### ISSUE TITLE
manufacturer relation config?

### ISSUE THREAD

**Issue by pisaniej** [bb-Ricardo/netbox-sync#145]
Is it possible to either map manufacturer, or ignore updating the manufacture once it has been synced?

For example, after running a sync I end up with both `Dell` & `Dell Inc.` and `Cisco Systems` & `Cisco Systems Inc`.

Additionally, device types also sometimes show up with type numbers like  `System x3650 M5 -[5462AC1]`, rather than a clearer `System x3650 M5`

**Comment by bb-Ricardo** [comment]
Hi,

sorry for the late answer. I thought about this as well. I might just add a config switch like the one with the primary IP.

https://github.com/bb-Ricardo/netbox-sync/blob/a9f25a630756f71f26ad845bc5d8dad86e355931/settings-example.ini#L200-L214

What do you think?

**Comment by neuro42** [comment]
This still leaves a manual reconfiguration needed every time a device is auto added with one of the duplicate manufacturers, and if one is cleaning up the dupes, having the dupe recreated/deleted every time this happens.  I think a mapping would be more useful to keep the flow automated.  It might also be useful to have mapping config for the most common of these in the defaults.

**Comment by bb-Ricardo** [comment]
Thanks again for this ideas.

The predifined mappings sound great.

Would define regex matches for the most common vendors in a file which is easy extendable. Don't know if a config option with an additional mapping would help much as all options should eventually end up in the mapping file.

What do you think?

**Comment by neuro42** [comment]
Sounds good.  Right now I get multiple instances of several vendors, with no way to really fix it.

**Comment by bb-Ricardo** [comment]
Hi @neuro42, @pisaniej,

I just pushed a new commit to "development".

Here you can find the mapping: https://github.com/bb-Ricardo/netbox-sync/blob/71c97dee1b278f87591ea56ca778b39fe4e64edb/module/netbox/manufacturer_mapping.py


Testing highly appreciated.

**Comment by pisaniej** [comment]
> Hi @neuro42, @pisaniej,
> 
> I just pushed a new commit to "development".
> 
> Here you can find the mapping: https://github.com/bb-Ricardo/netbox-sync/blob/71c97dee1b278f87591ea56ca778b39fe4e64edb/module/netbox/manufacturer_mapping.py
> 
> Let me know if you are missing any vendors
> 
> Testing highly appreciated.


@bb-Ricardo just tested this out, and seems to solve this issue, thank you! I will test it a few more times just to be certain.
