### ISSUE TITLE
parent tag synching

### ISSUE THREAD

**Issue by ShmoeTheHo** [bb-Ricardo/netbox-sync#146]
is it not possible to tag a cluster and have the vms underneath it inherit that tag in vmware? trying to automate tagging of machines in particular clusters but it doesn't seem to be coming through unless it's a vm folder or a vm itself.

Thanks!

**Comment by bb-Ricardo** [comment]
Hi, this is correct, only the folder tag of a VM will be read if parent tag sync is enabled.

I could add a `sync_vm_cluster_tag` option to enable this behavior.

But I would like to not end up with even more and more config options.

Or would there even be a better way to configure the tag syncing? Any suggestions?

**Comment by ShmoeTheHo** [comment]
The language on the existing setting is a bit ambiguous and could already imply this happens, not really sure how to proceed there. We've worked around this (crappily) in the mean though.

**Comment by bb-Ricardo** [comment]
I guess I should rephrase the config setting then.

**Comment by bb-Ricardo** [comment]
Hi,

I just changed the whole setting to tag syncing. Would you mind test the latest "development" branch?

https://github.com/bb-Ricardo/netbox-sync/blob/ae169125b7f48e5bbf5d7b4b45ccb61cc50050fa/settings-example.ini#L264-L275

Thank you
