### ISSUE TITLE
Customise key which defines VMware host primary interface

### ISSUE THREAD

**Issue by ShmoeTheHo** [bb-Ricardo/netbox-sync#154]
Requesting the ability to be able to customize the text search on the vswitch port groups for primary ip assignment -- currently harddcoded to "Management" and "Mngt" 

Thanks!

**Comment by bb-Ricardo** [comment]
Thank you, will add it in the next rlease

**Comment by bb-Ricardo** [comment]
just added, @ShmoeTheHo can you please test it?
