### ISSUE TITLE
Site detection faulty

### ISSUE THREAD

**Issue by ocstaron** [bb-Ricardo/netbox-sync#155]
Please correct module/sources/common/source_base.py

Line 266 should be

site_name = grab(device_object, "data.site.name")

instead of

site_name = grab(device_object, "data.site.data.name")

After this fix, site VRF and Tenant detection works again.

Kind regards and thanks,
Oliver

**Comment by bb-Ricardo** [comment]
Hi Oliver,

Thank you for this great hint. This ~is~ was indeed a bug. It should be fixed now: https://github.com/bb-Ricardo/netbox-sync/commit/b7422791220069bb422309644a14622f18dfaea7

Can you check out the branch 'development' and see if it works for you? That would be great.

**Comment by bb-Ricardo** [comment]
fixed in version 1.2.3
