### ISSUE TITLE
Role is overwritten on update

### ISSUE THREAD

**Issue by WaaZaa666** [bb-Ricardo/netbox-sync#16]
Hi again, 

Now the sync is working correctly, I am having the issue that my defined role is overwritten when the sync runs. 
I currently have the following highlevel flow for provisioning a VM:
Ansible create VM --> Register in Netbox with this specific VM's role <-- AWX inventory syncs with netbox (uses roles)
After some time netbox-sync comes around to ensure the specifics are up to date (CPU/mem/IP) in case this changed. 

I would like to have the option to NOT overwrite the VM role if it allready has been set. Am I missing a way I could achieve this?

**Comment by bb-Ricardo** [comment]
I could also change it into: set if undefined. pretty much like primary_ip

**Comment by WaaZaa666** [comment]
Yep, that would be good. I can imagine other users would have issues having a single role for all VM's as well.

**Comment by bb-Ricardo** [comment]
Also makes totally sense. I just changed it. can you pull again and test?

**Comment by WaaZaa666** [comment]
Working as I wished. Thanks again!
