### ISSUE TITLE
Device data structure primary key

### ISSUE THREAD

**Issue by rizlas** [bb-Ricardo/netbox-sync#162]
Hi,
currently I'm getting these errors:

> ERROR: This 'device' data structure does not contain the primary key 'name'

Name is set to None cause it is not a mandatory field. Even stranger these errors are shown for object that are not in any sources defined in settings nor they have any tag netbox-sync related.

**Comment by bb-Ricardo** [comment]
I'm a bit confused:

According to the OpenAPI specification of NetBox: https://demo.netbox.dev/api/docs/

the attribute `name` is a required field and can't be empty. The returned data in this example from #157 shows a `"None"`. Which is a string.

```json
{
   "id":21125,
   "url":"https://netbox/api/dcim/devices/21125/",
   "display":"Cable Management 1U Cable Management (21125)",
   "name":"None",
   "device_type":{
      "id":137,
      "url":"https://netbox/api/dcim/device-types/137/",
      "display":"1U Cable Management",
      "manufacturer":{
         "id":29,
         "url":"https://netbox/api/dcim/manufacturers/29/",
         "display":"Cable Management",
         "name":"Cable Management",
         "slug":"cable-management"
      },
      "model":"1U Cable Management",
      "slug":"1u-cable-management"
   },
   "device_role":{
      "id":30,
      "url":"https://netbox/api/dcim/device-roles/30/",
      "display":"Cable Management",
      "name":"Cable Management",
      "slug":"cable-management"
   },
   "tenant":"None",
   "platform":"None",
   "serial":"",
   "asset_tag":"None",
   "site":{
      "id":1,
      "url":"netbox/api/dcim/sites/1/",
      "display":"Site01",
      "name":"Site01",
      "slug":"site01"
   },
   "location":{
      "id":4,
      "url":"https://netbox/api/dcim/locations/4/",
      "display":"DC01",
      "name":"DC01",
      "slug":"dc01",
      "_depth":0
   },
   "rack":{
      "id":2937,
      "url":"https://netbox/api/dcim/racks/2937/",
      "display":"rack02",
      "name":"rack02"
   },
   "position":36,
   "face":{
      "value":"rear",
      "label":"Rear"
   },
   "parent_device":"None",
   "status":{
      "value":"offline",
      "label":"Offline"
   },
   "airflow":"None",
   "primary_ip":"None",
   "primary_ip4":"None",
   "primary_ip6":"None",
   "cluster":"None",
   "virtual_chassis":"None",
   "vc_position":"None",
   "vc_priority":"None",
   "comments":"",
   "local_context_data":"None",
   "tags":[
      
   ],
   "custom_fields":{
      "support end date":"None",
      "support provider":"None"
   },
   "created":"2017-06-26",
   "last_updated":"2020-11-17T17:03:19.064701-07:00"
}
```

If it is an actual None/null then this data should not even return from NetBox.

Is it possible to schedule a debug session? would be highly interested in finding out what's going on.

**Comment by rizlas** [comment]
Yeah a debug session would be fine for me.

About Device model, if you check it you can see that name isn't mandatory

https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/models/devices.py#L474

Even the api serializer doesn't specify anything about the name field

https://github.com/netbox-community/netbox/blob/develop/netbox/dcim/api/serializers.py#L452

**Comment by bb-Ricardo** [comment]
Mhh, I have the feeling that the swagger ui output  does not match the source.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/771836/160593677-03509e08-fcef-47e8-8c48-511390168b21.png">

I'm confused.

**Comment by bb-Ricardo** [comment]
ohh this might be the "issue":
https://github.com/netbox-community/netbox/blob/894665b067616cb7b29c4522460f55daf53f3e61/netbox/dcim/models/devices.py#L598-L604

As "name" is not mandatory anymore to define uniqueness it can also be None.

* One solution could be to ignore device without `name` while parsing devices from NetBox.
* Another solution: add all uniqueness combinations (much harder)

What do you think?

**Comment by rizlas** [comment]
This is a valid json and will create a device.

```
{
    "name": null,
    "device_type": 142,
    "device_role": 29,
    "tenant": 1,
    "site": 83,
    "rack": 41,
    "face": null,
    "virtual_chassis": null
}
```
I think uniqueness is already there when you try to add a device with netbox-sync, isn't it?
Also data gathered from different source has always a name, at least for vCenter. Imho ignore them should be fine.

**Comment by bb-Ricardo** [comment]
In the end it was just a log message. I pushed a change to "development" branch to ignore this on devices read from NetBox.

Would be great if you could check it out and test it.

Thant you

**Comment by rizlas** [comment]
Yeah thank you, I will come back to you as soon as I test it

**Comment by rizlas** [comment]
Confirm, this is not an error log anymore. Here is the output:

> 2022-03-29 17:53:26,817 - DEBUG2: This 'device' data structure does not contain the primary key 'name'. Skipping

Maybe output of an ID should add more sense to the line.

**Comment by bb-Ricardo** [comment]
how about this?

**Comment by rizlas** [comment]
Very good, for me is enough. Thank you!

> 2022-03-30 09:29:05,971 - DEBUG2: This 'device' (291) data structure does not contain the primary key 'name'. Skipping. Link: http://netbox:8080/api/dcim/devices/291/
