### ISSUE TITLE
Publish docker image to docker hub

### ISSUE THREAD

**Issue by ftaeger** [bb-Ricardo/netbox-sync#168]
Hi,

I really like your tool but it might be a lot easier to consume when it's being pushed to docker hub so we can just pull and run the image rather than building it first. Might be little effort for you but can help out quite a lot since a lot of folks out there is running stuff on servers that can't access the internet in general but limited sources (like docker hub) only ... 

And sure I could probably do this myself but where's the point if I would just copy the repo 1:1 which might result in outdated versions or whatever ... ;-) 

I just like the convenience of consuming a good tool as is rather than adding no value but work by myself ;_)

**Comment by bb-Ricardo** [comment]
very good point. How about the github docker registry?

**Comment by ftaeger** [comment]
I guess I still prefer hub.docker.com but I take what you provide. Might not need to be either A or B but both registries though ;-)

**Comment by bb-Ricardo** [comment]
like this?: https://hub.docker.com/r/bbricardo/netbox-sync

**Comment by bb-Ricardo** [comment]
I still need to change the path from `/opt` to `/app`. So please wait for the next version.

**Comment by ftaeger** [comment]
Haha. Yeah. Just like that. Nice one. ;-)

**Comment by bb-Ricardo** [comment]
"fixed" in version 1.2.3
