### ISSUE TITLE
Option to have Cluster Group created as the VC Name instead of Datacentre name

### ISSUE THREAD

**Issue by chrisclarke6710** [bb-Ricardo/netbox-sync#171]
Feature request, as per query on 27th Feb:

I'm testing the Netbox_sync script and does a great job on overall.
However Currently the Cluster Group is linked to the Datacentre object name within the VC.
I understand the reasoning for this however, it would be good to have the option to create Cluster Groups based on the VC name rather than Datacentre name.
Reason:
When supporting multiple VC servers in the same DC (used for different purposes) all configured to use the same Datacentre name, it becomes very confusing to which VC a VM and Cluster belongs too.

Ideally the option to have the Cluster Group created as the VC name, and then the datacentre name as custom attribute of the Cluster.
This also allows the Cluster Group to have a custom field with a link to the VC (this doesnt need to be provided by the script though).  

Many thanks

**Comment by bb-Ricardo** [comment]
Hi @chrisclarke6710,

I added this to the "development" branch. Can you check it out and test if this works?
