### ISSUE TITLE
interface naming

### ISSUE THREAD

**Issue by neuro42** [bb-Ricardo/netbox-sync#175]
Currently, interfaces get named/updated to the following sort of naming:
INFO: Created new virtual machine interface object: vNIC 1 (vlanname) (hostname)

Wanting to use netbox as a source of truth that network interface config can be generated from for VMs; for this to work the interface name has to match what the OS uses, such as "eth0" "eno1" or "ens224".  Given that the OS names can be anything these days, it would be hard to come up with the correct names from vcenter data, so just a way to only update the name when the name is undefined would be enough here.

**Comment by bb-Ricardo** [comment]
Hi,

I try to understand what you mean hear but don't really get.

Can't remember if the OS interface name is exposed via guest tools. And would only be available if the guest tools are installed and running.

You could run the tool with `-l DEBUG3`. There you should get all the available VMWare API details.

**Comment by neuro42** [comment]
afaik, the interface names aren't exposed.  I just need a way to not have netbox-sync overwrite the interface names on each run so they can be updated on the netbox side to match the OS assigned names.  I'm not sure what netbox-sync is using as the key between the two, so hopefully this is actually possible.

**Comment by bb-Ricardo** [comment]
Ahh ok, I could easily add a config option like the primary_ip one to not overwrite the interface name.

The process of matching interfaces is described here: https://github.com/bb-Ricardo/netbox-sync/blob/main/docs/common_concepts.md

**Comment by bb-Ricardo** [comment]
Hey @neuro42,

this took a while. I added config option to disable interface name overwrite:
```ini
# define if the name of the (device/VM) interface discovered overwrites the interface name in NetBox
#overwrite_device_interface_name = True
#overwrite_vm_interface_name = True
```
Can you please pull the newest `development` branch and test it out? Thank you very much.

**Comment by bb-Ricardo** [comment]
closed due to no response
