### ISSUE TITLE
Assign a Cluster site to None

### ISSUE THREAD

**Issue by 3bruno** [bb-Ricardo/netbox-sync#184]
Hi. I have a Cluster that has devices from two different sites and when I run the script I get an error as the script is filling the cluster attribute 'site' for a specific site and only 1 device is imported.
Is it possible to not set the 'site' cluster attribute when running netbox-sync?

**Comment by bb-Ricardo** [comment]
Hi,

this is not really possible as there are a lot of attributes which depend on the site definition. Finding the correct VLAN for example. So I'm not really sure how to solve your setup.

Maybe you can explain it in more details and the constrains.

**Comment by sliddjur** [comment]
> devices from two different sites
I think the best way to solve this is to:
- separate vcenter clusters with hosts belonging only to one site.
- filter settings.ini and make cluster and devices point to your desired site.

your other option is to only have one "vcenter-site" in netbox and put everything in there (but then you cant rack your esxi-hosts on the "real" site)

**Comment by 3bruno** [comment]
Hi all. Thanks for your update.

sliddjur... I did the second way! Created one "vcenter-site" and put all cluster them, but the phisical hosts I keep on the correct site to follow the rack bayface.

**Comment by bb-Ricardo** [comment]
@3bruno did this solve your issue?

**Comment by 3bruno** [comment]
@bb-Ricardo As workaround I created one "vcenter-site" and put all cluster them. 

You can close this issue.

Thank you.
