### ISSUE TITLE
Script error after update to NetBox 3.2.2

### ISSUE THREAD

**Issue by Houtek** [bb-Ricardo/netbox-sync#185]
Hi,

after updating to NetBox 3.2.2 I receive this error:
`AttributeError: 'NoneType' object has no attribute '__name__'`
[Here is the complete error message](https://gist.github.com/Houtek/5a98cca7f8a3969a4d24753562ac6fc7)

Do you have an idea, where this error comes from?

Edit: The current development and stable versions of netbox-sync work without any issue on NetBox 3.2.1

**Comment by bb-Ricardo** [comment]
Ui, they might have changed some API endpoints again. Will need to test it again against 3.2.2.

I'm sure I did this already.

**Comment by neuro42** [comment]
This is the same error message seen without higher debug enabled when there's an fhrpgroup defined; I still get to that point and see this error with 3.2.2

**Comment by bb-Ricardo** [comment]
is this similar to this issue? https://github.com/bb-Ricardo/netbox-sync/issues/174

**Comment by Houtek** [comment]
We don't have fhrpgroups in our Netbox, I could send you a debug log with more information by mail, if it helps you.

**Comment by bb-Ricardo** [comment]
Hi, yes please. Usually helps to understand the issue better.

You can find my mail address here: https://github.com/bb-Ricardo/netbox-sync/blob/d0143119de99fd40e39e923fe111045a85796b96/netbox-sync.py#L30

Thank you.

**Comment by Houtek** [comment]
I sent you a mail with some logs.

**Comment by bb-Ricardo** [comment]
This issue has been fixed
