### ISSUE TITLE
Mention change in custom fields name in change description.

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/netbox-sync#190]
https://github.com/bb-Ricardo/netbox-sync/discussions/178#discussioncomment-2745620

**Comment by juliouzzzz** [comment]
Hi, 
After update to netbox 3.2.2 and netbox-sync last in dev branch i had some error with vmware custom attributes as i mention in https://github.com/bb-Ricardo/netbox-sync/discussions/178#discussioncomment-2745620

my old custom field created by netbox-sync was "vcsa_last-backup", my new field created by new netbox-sync was "vcsa_last_backup".

What i did : 
- change description of OLD custom field
- delete OLD custom field in netbox 
- configure table in list with new available column of new custom field

Julien

**Comment by bb-Ricardo** [comment]
Text:

If you're upgrading from older NetBox versions be aware of the change of custom_fields.
Only `_` are allowed since 3.2 and `-` are not permitted anymore.
example: `vcsa_last-backup` will turn into `vcsa_last_backup`

What you need to do in NetBox:
* change description of OLD custom field
* delete OLD custom field in NetBox
* configure table in list with new available column of new custom field in NetBox after the sync completed
