### ISSUE TITLE
FR: Add summary hardware infos on devices

### ISSUE THREAD

**Issue by juliouzzzz** [bb-Ricardo/netbox-sync#191]
Is it possible to push summary CPU/RAM/DISK on custom field on "devices" like netbox-sync do on VirtualMachines

Thanks

NB : refers to this discussion : https://github.com/bb-Ricardo/netbox-sync/discussions/189#discussioncomment-2746471

**Comment by bb-Ricardo** [comment]
thank you

**Comment by bb-Ricardo** [comment]
CPU and RAM have been added. Disk is not exposed via VMWare API.
