### ISSUE TITLE
Netbox Group is set to "host" when Host/Cluster Folder is used inside a datacenter

### ISSUE THREAD

**Issue by RobiRob81** [bb-Ricardo/netbox-sync#195]
Hi,

when a cluster is placed inside a host folder in a datacenter, the import change the "Cluster Group" to "host" and not the Foldername.

Example:
Datacenter --> TEST --> Cluster01
Group will be set to "TEST".

Datacenter --> TEST2 --> Folder: SiteA --> Cluster-Site-A-01
Group will be set to "host".

thanks,
Robert

**Comment by bb-Ricardo** [comment]
Thank you for this info. This seems interesting and should not be happening.
I'm currently rewriting this part about cluster and group detection due to an another issue.
Will let you know when it's ready for testing.

**Comment by RobiRob81** [comment]
Hi @bb-Ricardo

just used the dev branch version.
What i see in a dry run is that only the same cluster will created and each VM under the cluster will be reassigned.
But it's still the same name.

INFO: Created new cluster object: testcluster01
INFO: Virtual machine 'VMTEST01' attribute 'cluster' changed from 'testcluster01' to 'testcluster01'
INFO: Virtual machine 'VMTEST02' attribute 'cluster' changed from 'testcluster01' to 'testcluster01'
....
INFO: Cluster group 'host' attribute 'tags' changed from '['NetBox-synced', 'Source: vsphere']' to '['Source: vsphere']'

I don't see a new group assignment.

If i manually change in netbox the cluster group to the desired folder then i just see this additional line from a new run.
INFO: Cluster group 'host' attribute 'tags' changed from '['NetBox-synced', 'Source: vsphere']' to '['Source: vsphere']'

All runs are only with "dry run".
Does it matter to do it only with dry run?

thanks,
Robert

**Comment by bb-Ricardo** [comment]
Hi, It might seem as the same cluster but it isn't. It has a different group. The problem is that multiple clusters with the same name can be created in NetBox. That's why it seems like the same cluster (name wise) but it isn't.

But your actual issue with 'host' as cluster name has been resolved?

Dry run tells you what changed but does not change it in NetBox.
