### ISSUE TITLE
tags incompliant with ansible

### ISSUE THREAD

**Issue by DanielWeeber** [bb-Ricardo/netbox-sync#198]
Hey, thank you very much for netbox-sync. I'm using this to sync my VMware VMs to netbox, obviously. But also I am using the netbox dynamic inventory for ansible, which syncs everything from netbox to an ansible directory file
Unfortunately you are using incompliant tagnames

any way to change that?

```

Not replacing invalid character(s) "{'-'}" in group name (tags_netbox-synced)
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
Not replacing invalid character(s) "{'-'}" in group name (tags_source-vcenter)
```

**Comment by bb-Ricardo** [comment]
Hi,

Great that you have use for the script.

According to the API documentation there is no restriction on the character to use in a tag. The slug can also contain '-' and a '_'.

https://demo.netbox.dev/api/docs/

If this is issue then the ansiblen inventory needs to take care of checking and converting invalid characters as this is a general issue and not limited to netbox-sync.

Would you mind opening an issue here: 

https://github.com/ansible/ansible/issues

Thank you.
