### ISSUE TITLE
[IP Addresses] : IP Address don't have a tenant. 

### ISSUE THREAD

**Issue by GaxSkilton2** [bb-Ricardo/netbox-sync#199]
When I execute the script all VMs and sites are associated with a tenant but IP Addresses aren't. 
Is that a configuration issue ?

**Comment by bb-Ricardo** [comment]
Nope, it is just not implemented.

Will have a look.

**Comment by bb-Ricardo** [comment]
Hi, can you checkout the "development" branch and see if it works now?

**Comment by GaxSkilton2** [comment]
Hello, 
I just did a pull this morning
I used the commit 3e0532a25bc8f49d588dc911ba20eac77a69da7a on the dev branch.

**Comment by bb-Ricardo** [comment]
Jup, I just did a new commit with a fix in it.

**Comment by GaxSkilton2** [comment]
Hello, 
It's working. 
Can you do the same for VLANs?

**Comment by bb-Ricardo** [comment]
Hi, I just pushed another commit. Can you test it out and see if this works now?

thank you

**Comment by bb-Ricardo** [comment]
Great, thaks for testing.

**Comment by bb-Ricardo** [comment]
Also remove the tenant assignment to VLANs again. Using the devices tenant is a bad default.
