### ISSUE TITLE
new version, bugs, questions

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#2]
installed a new version today
1) after running the script, I get an error FileNotFoundError: [Errno 2] No such file or directory: 'cache / NBPlatforms.cache'
2) installation instructions
virtualenv .env - there is no such command on centos
3). .env / bin / activate - after entering this command - system response No such file or directory
4) pip install -r requirements.txt - I think you need to add to the instructions what you need to run like this
pip3 install -r requirements.txt
5) in the config file I chose like this
type = vmware, I have vcenter - is this correct?
6) I don't understand the cluster_site_relation function
, for example, I have several clusters (on a screenshot), how can I write them correctly in this function?
![image](https://user-images.githubusercontent.com/36307887/98461466-fac55b80-21b4-11eb-873d-fb2d416145a0.png)

**Comment by bb-Ricardo** [comment]
Hi, thanks again for the detailed testing.

The description is far from finished. I will test and describe all the questions you pointed out in the README.

Yes, vmware is meant to be vcenter. The API should also work by directly talking to an ESXi host but I haven't tried that at all.

A site in NetBox adds relation to certain networks, vrfs, ressources and more. If you have two sites like "New York" and "Tokyo" then it could be possible to have the same private subnet in both sites. And to add VM or host IP addresses to the correct subnet/prefix we need to know where the vm is located.
