### ISSUE TITLE
Detecting esxi hosts as the same box

### ISSUE THREAD

**Issue by CodeNameTheOnlyOne** [bb-Ricardo/netbox-sync#202]
when i run the sync for all of my intel hosts the utility thinks they are all one piece of hardware that results in it not creating more than one host and just thinking the data has ben updated and just overwriting it with the next host.
im guessing is because these are oem boards with no/same serial number.
seems like this is only effecting my intel servers.
any idea how to resolve this?
i tried creating a new device with the ip of one of the hosts but it did not want to populate it.
guessing its mapping based on the serial number, and it populates that with "............"

i will see if i can set the serial number on one of my servers but its going to be hard to take some of them offline.
is there a setting i can set in vcenter to let your script know they are different hosts?

**Comment by bb-Ricardo** [comment]
Hi,

yes, the serial number or the asset tag can be the issue. Happens sometime on Blade systems or SuperMicro server.

have you seen this option?:
https://github.com/bb-Ricardo/netbox-sync/blob/d0143119de99fd40e39e923fe111045a85796b96/settings-example.ini#L186-L189

Just try setting it to `False` and then try again.
