### ISSUE TITLE
[Purge] : How to purge specific tenant ? 

### ISSUE THREAD

**Issue by GaxSkilton2** [bb-Ricardo/netbox-sync#204]
Hello, 

I want to know if i edit « connection.py » to edit tag « Netbox-synced » and « NetBox-Orphanned ». 
Do you think when I purge one tenant it’s will no have impact on the other tenant ?! 

I have more than 20 tenant and I don’t wanna purge all. It’s possible ?  

Thank you.

**Comment by bb-Ricardo** [comment]
I don't really know what you want to do here.

It is not possible to purge specific tenants.

What is your scenario? Maybe we can come up with a different solution.
