### ISSUE TITLE
Skip VLAN update/creation

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/netbox-sync#205]
### Discussed in https://github.com/bb-Ricardo/netbox-sync/discussions/85

<div type='discussions-op-text'>

<sup>Originally posted by **nes-achimg** September  1, 2021</sup>
At the moment I am testing your script against our Netbox installation. I have already done some customization regarding some custom_field configuration. But I am stuck now.
We define our VLANs outside of the Vcenter and, at the moment, those are added and updated manually. We don't want the sync script to tag, update or create any VLAN in Netbox. However, I cannot find the right place to stop the script from doing just that. I have already commented out the NBVLAN object in the Vcenter connection.py, but that doesn't have any effect on the update/creation process. I think, it only stops the initial population of the inventory.
Could you point me in the right direction?
I am looking at something like having an option in the settings.ini to switch that on or off.</div>

**Comment by christianahug** [comment]
Thanks for opening the issue - was just coming here to do that.

**Comment by bb-Ricardo** [comment]
Hi,

yeah, was a bit silly to ask. It only was one click in the UI anyway. Sorry.

I just pushed a change to the 'development' branch. Can you test it and let me know if it works for you?

Thank you.

**Comment by christianahug** [comment]
Just tested it and looks good so far - exactly what I was looking for. Thanks!

**Comment by bb-Ricardo** [comment]
great, thank you for testing
