### ISSUE TITLE
Netbox-sync 1.2.3 sync with 3.2.5 netbox

### ISSUE THREAD

**Issue by brmoney** [bb-Ricardo/netbox-sync#207]
Hi, @bb-Ricardo!
I want to ask a question: Can a netbox-sync pick up from the vCenter a new virtual machine?
If I added the ip manually, the netbox-sync does not update information on it from the vCenter. Netbox-sync successfully connects to netbox, successfully connects to vCenter, but does not update data on the virtual machine from vCenter to manually added ip in netbox. It doesn't show any debug3 when enabled, there is no such IP in the logs at all.
The same configurations work for a netbox 3.1.1 on a different server.
Tell me, please, what could be the problem?

**Comment by bb-Ricardo** [comment]
Hi,

It is auite hard to make any assumptions from your message.

Is the IP address in the range of permitted subnetworks?

**Comment by brmoney** [comment]
Yes, IP address in the range of permitted subnetworks.

**Comment by bb-Ricardo** [comment]
I can't really help here. I hVe no logs and no information. The sync should work if the IP address is exposed via VMtools to the vCenter. Make sure VM tools are installed in the VM.

**Comment by brmoney** [comment]
Thanks for the advice, I'll check it out.
What part of the logs should be provided if the required IP address is not mentioned at all in the logs during debug3?

**Comment by brmoney** [comment]
Thank you very much! I solved the problem by updating the utility to the version from the developer branch.
