### ISSUE TITLE
Skip updating attribute 'name'

### ISSUE THREAD

**Issue by jhammond-git** [bb-Ricardo/netbox-sync#21]
Thank you for running this project.

Would it be possible to have the option to skip updating the name of a host?  What we store in netbox is the upper case hostname, and what's being returned and set is the lower case FQDN.  For instance:

"INFO: Device 'esx-name.fqdn.local' attribute 'name' changed from 'ESX-NAME' to 'esx-name.fqdn.local'"

**Comment by bb-Ricardo** [comment]
Hi, that would be possible.

Would need a new config option though.

Not sure when I will get around doing this but should be a quite easy change.

**Comment by jhammond-git** [comment]
I was looking through the objects today.  An alternative, at least for me, would be to use vim.host.DnsConfig.hostname instead.  Not sure what you're using at this time.

**Comment by bb-Ricardo** [comment]
The name is the object name in vCenter not the DNS name. Are you able to rename the hosts objects in vCenter? Then the name would match.

**Comment by jhammond-git** [comment]
I will admit that I'm not a vcenter admin, just one of the network guys, but my understanding of how the newer versions of vcenter do things is that they require a DNS name for the host name, so it will always be the fqdn that's returned.  In the past we could use IP addresses, but not any more.  The DNS name is what holds the bare hostname in our setup.

Perhaps just having the option to not rename the host would be the most useful and I'm just complicating things.

**Comment by bb-Ricardo** [comment]
would the feature proposed in #29 solve your issue?

**Comment by jhammond-git** [comment]
Yes.

**Comment by bb-Ricardo** [comment]
Great, then I close this issue and will track it in #29. Thank your for the feedback
