### ISSUE TITLE
Tenant name is changed when longer than 30 characters

### ISSUE THREAD

**Issue by t8simon** [bb-Ricardo/netbox-sync#214]
Hi 

I noticed, that netbox-sync is changing the tenant name (and therefor slug) when the name is longer than 30 characters. 
In this case, the tenant name is cut to the first 30 characters. 

Expected behavior would be, that the tenant name is untouched if it has a match in the vm_tenant_relation. 

Maybe this 30 Char limit is existing in other places as well, but I did just notice it for the Tenants.

**Comment by bb-Ricardo** [comment]
will hie a look into it

**Comment by t8simon** [comment]
This also leads to the following error messages: 
` ERROR: Unfortunately updated item tenant for object <vm-name> could not be fully resolved: <NBTenant instance '<shortened tenant>' at 140590282668128>`

**Comment by bb-Ricardo** [comment]
Hi, I just pushed a change for this to the `development` branch. Indeed the length of quiet a few models has changed. I adjusted them according to the API specs. It should work better now.

**Comment by t8simon** [comment]
So, the errors are gone and no tenant names are changed. 

How ever, the vm creation fails on the development branch. It has the same error message as in Issue https://github.com/bb-Ricardo/netbox-sync/issues/220 .

I am however on version 3.2.7, not 3.3.0. I added a note there with my findings.

**Comment by bb-Ricardo** [comment]
Hi,

Thank you very much for testing. Unfortunately I can't see your note on the issue.

**Comment by bb-Ricardo** [comment]
Sorry, I guess i was to quick.
