### ISSUE TITLE
Odd changes every run

### ISSUE THREAD

**Issue by ksalman** [bb-Ricardo/netbox-sync#215]
Hello,
Every time I run netbox-sync, it keeps making these weird change where it changes the name of the ESXi host from one to another and even the cluster that host is in

```
2022-08-15 17:14:53,326 - INFO: Device 'us-rtp-1' attribute 'name' changed from 'us-rtp-2' to 'us-rtp-1'
2022-08-15 17:14:53,326 - INFO: Device 'us-rtp-1' attribute 'cluster' changed from 'DEV' to 'PROD'
2022-08-15 17:14:53,326 - INFO: Device 'us-rtp-1' attribute 'device_type' changed from 'S2600WP' to 'S2600TP'
2022-08-15 17:14:53,327 - INFO: Device 'us-rtp-1' attribute 'serial' changed from 'ABCD' to 'WXYZ'
```

There are two separate devices us-rtp-2 and us-rtp-1. It is doing this type of changes with other hosts as well. I didn't make those changes in vCenter. What's even more odd is that netbox-sync has not created a record for device us-rtp-1 in Netbox.

**Comment by bb-Ricardo** [comment]
Hi, are these devices using the same serial number or asset tag by any chance? You can set the log level to DEBUG2 and see  what's happening there.

**Comment by ksalman** [comment]
Oh I see. Looking at hardware info in vCenter, all these devices have the same bogus asset tag of `....................`
```
 Model: S2600TP, Serial Number: XYZ, Tag: XYZ, Other Identifying Info: Asset Tag: .................... 
```

In my `settings.ini` I added `collect_hardware_asset_tag = True` and that seems to work. Is there a better way to tell netbox-sync to not use asset_tag for matching?

**Comment by bb-Ricardo** [comment]
It should all be fine once you set it to False.

**Comment by ksalman** [comment]
Ok, thank you for the help. I'll go ahead and close this issue.
