### ISSUE TITLE
Move vm from one cluster to another

### ISSUE THREAD

**Issue by swe-mbernhard** [bb-Ricardo/netbox-sync#219]
Thankyou for an excellent piece of software, very useful indeed. 
I have an idea for enhancement though. I would find it very useful if there would be an option to be able to move VM from one cluster to another, and update the row in the database. 
As it works today, if I move a VM from a cluster to another, the old entry will be orphaned, and a new one will be created. I do run a postgresql query to copy the tenant_id from the old VM to the newly created, but I will lose the history of the vm when the old one gets purged. 
So, an update of the cluster id would be nice, instead of inserting a new row and orphan the old one. Of course as an option in the settings file. 
Best regards
/
Markus

**Comment by bb-Ricardo** [comment]
Hi Markus,

Not sure if that is an easy task. Can you manually assign the new cluster to the VM in NetBox before you run the sync?

**Comment by swe-mbernhard** [comment]
Hi Ricardo, thanks for your prompt reply!

Unfortunately that is not an option for us, since vm:s can be migrated to different clusters by anyone. 

Another viable solution would be to have the option to skip cluster import, then it wouldn't be a problem.
Best regards
/ Markus

**Comment by bb-Ricardo** [comment]
mhh, valid point. not sure if it is so easy. Would need to track the VM via UUID and then recognise changes in the cluster.

will think about that.

**Comment by bb-Ricardo** [comment]
Can you enable an option in your vCenter sync
```ini
vm_custom_object_attributes = config.uuid,config.instanceUuid
```

and check if they stay the same on moving the vm from one cluster to the other?

Thank you

**Comment by bb-Ricardo** [comment]
Hey, was wondering if this still relevant?
