### ISSUE TITLE
check for global VLAN if site VLAN is not present

### ISSUE THREAD

**Issue by Epaphus** [bb-Ricardo/netbox-sync#22]
I'm having issues with VLANs being duplicated, we treat each VLAN ID as being globally unique even if a VLAN only exists in one site.
If a VLAN is only in one site then it gets tagged with that site, if its on multiple vCenters for VMs with DR or spanned across multiple sites then it doesn't get tagged with a site within Netbox.

The issue is that after we run a sync we end up with multiple copies of the same VLAN.
For example, VLAN 123 might be in Netbox without being tagged to a site, after the sync it will show 3 times, the original VLAN we created plus 2 extra (one for each vCenter site).
With the prefixes, etc being assigned to existing VLANs we created it kinda makes a mess of things having the duplicated VLANs.
For example the VM interfaces are attached to the duplicated VLAN not the same VLANs we attached the the prefixes to.

Would it be possible to have an option within netbox-sync to match the VLANs in Netbox with the vCenter VLANs based on ID only and not ID and site? 
I believe this would stop the VLAN duplication issue we are seeing.

**Comment by bb-Ricardo** [comment]
Hey,

This is possible to solve. I will try to implement it next year. The IP addresses already work that way. First we look for a prefix with the same site and then we look for global prefixes. Could do the same with VLANs.

**Comment by bb-Ricardo** [comment]
I added a change to master. Can you try it out and report if it's working now?

New behavior:
* check for VLAN with same ID in the same site
* if not found check for VLAN with same ID and no site attached
* if nothing was found a new VLAN within the site will be created

**Comment by Epaphus** [comment]
Looking good.

Many thanks.

**Comment by bb-Ricardo** [comment]
Great, thank you for testing.
