### ISSUE TITLE
Errors after script update

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#223]
netbox 3.3.1
netbox-sync  1.3.0-beta3

1) log file is not created (I created the folder manually) but the folder is empty. I set the DEBUG2 parameter but the log was not created.
2) virtual machines are not created, only IP addresses to them
3) Such error for each server.
`2022-08-29 11:42:11,236 - DEBUG: Parsing vCenter host: 192.168.50.150
2022-08-29 11:42:11,620 - ERROR: Requesting cluster for host '192.168.50.150' failed. Skipping.
2022-08-29 11:42:11,696 - DEBUG: Parsing vCenter host: 192.168.50.110
2022-08-29 11:42:12,081 - ERROR: Requesting cluster for host '192.168.50.110' failed. Skipping.
2022-08-29 11:42:12,158 - DEBUG: Parsing vCenter host: 192.168.50.180
2022-08-29 11:42:12,537 - ERROR: Requesting cluster for host '192.168.50.180' failed. Skipping.
2022-08-29 11:42:12,613 - DEBUG: Parsing vCenter host: 192.168.50.145
2022-08-29 11:42:12,994 - ERROR: Requesting cluster for host '192.168.50.145' failed. Skipping.
2022-08-29 11:42:15,440 - ERROR: Requesting cluster for host '192.168.50.200' failed. Skipping.
2022-08-29 11:42:15,517 - DEBUG: Parsing vCenter host: 192.168.50.250
2022-08-29 11:42:15,898 - ERROR: Requesting cluster for host '192.168.50.250' failed. Skipping`

2022-08-29 12:17:09,469 - DEBUG: Parsing vCenter host: 192.168.50.250
2022-08-29 12:17:09,851 - ERROR: Requesting cluster for host '192.168.50.250' failed. Skipping.
2022-08-29 12:17:10,077 - ERROR: (vmodl.query.InvalidProperty) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   name = 'answerFileValidationResult'
}

**Comment by bb-Ricardo** [comment]
Hi, thank you for the testing. would you mind doing some A-B testing?

using 1.2.3 agains 3.3.1 
using 1.3.0-beta3 against 3.2.9

I also checked my code again. Nothing has changed with the code for logging between 1.2.3 and 1.3.0. So I don't know why it isn't working for you. If you delete the log folder, do you get any ERROR messages?

**Comment by SerhiiZahuba** [comment]
I'm sorry. According to the logs - this is my mistake in the config.

If use using 1.2.3 agains 3.3.1

then the error is only

 - DEBUG2: Received HTTP Status 400.
2022-08-29 12:56:39,603 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
2022-08-29 12:56:39,603 - ERROR: NetBox returned body: {'cluster': ['The selected cluster (192.168.110.160 is not assigned to this site (None).']}


New virtual machines are not created.

**Comment by bb-Ricardo** [comment]
This message `{'cluster': ['The selected cluster (192.168.110.160 is not assigned to this site (None).']}` looks like an NetBox issue. It should not state 'None'!

**Comment by SerhiiZahuba** [comment]
The development branch did not help me. New virtual machines are not created. I see this error in the log.

`2022-08-31 14:32:34,981 - ERROR: (vmodl.fault.SystemError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = 'unexpected error reading property'
}
`

**Comment by danilutkin** [comment]
Same:
2022-08-31 13:39:31,461 - DEBUG: Parsing vCenter host: hostname
2022-08-31 13:39:31,854 - ERROR: Requesting cluster for host 'hostname' failed. Skipping.

**Comment by bb-Ricardo** [comment]
you both use standalone ESXi hosts?

**Comment by danilutkin** [comment]
Yes, I am)

**Comment by bb-Ricardo** [comment]
Ahh, I assumed. I changed the way how parent objects in vCenter are discovered. I guess the vCenter API is not happy with this way. I will have a look but can't promise a quick solution.

**Comment by danilutkin** [comment]
Thank you! I will try to wait you out)

**Comment by bb-Ricardo** [comment]
are you up for a debug session? Then we could try to figure it out together. I lack a vCenter with that setup.

**Comment by SerhiiZahuba** [comment]
I could not find your email, please write me when you download the log, I will delete it. Thanks
[netbox_sync.gz](https://github.com/bb-Ricardo/netbox-sync/files/9463002/netbox_sync.gz)

**Comment by bb-Ricardo** [comment]
done

**Comment by vacumet** [comment]
I got the same type of issues at my computer club. I have a mix of both vmware clusters and standalone hosts. Tell me if you need anything. 
Running the development branch of netbox-sync and netbox 3.3.1 in combination with vcenter 6.7 that is the best match for the mix of old hardware we use.

**Comment by danilutkin** [comment]
Plus one, I could do some tests to. 
For example, in my case of standalone only hosts worked v1.2.3 tagged commit.

**Comment by bb-Ricardo** [comment]
Hey, I would highly appreciate a copy of a vCenter.

It could also be a test vCenter with this single host setup.

Here is an article how to export your configuration: https://williamlam.com/2021/01/record-and-replay-vsphere-inventory-using-govc-and-vcsim.html

I currently have no test environment where I can just play around and set up stuff.

Then I could just add it to my test setup and test against it on every release.

That would make the development process much easier and I would be very happy about it. Solving this issue probably would not take more then 30 minutes.

Thank you.

**Comment by vacumet** [comment]
I will try to message you a zip file with the output from govc @bb-Ricardo

**Comment by bb-Ricardo** [comment]
If mailing fails due to the size just write a regular mail and we figure out another way. I highly appreciate your efforts.

**Comment by vacumet** [comment]
The file is only 2.5MB but i can't find your email :)

**Comment by bb-Ricardo** [comment]
there it is: https://github.com/bb-Ricardo/netbox-sync/blob/5a8ce969b9fdba14dd8377789da269cf348027c7/netbox-sync.py#L30

**Comment by vacumet** [comment]
I hope it works as planned. Thank you for a great script!

**Comment by bb-Ricardo** [comment]
> I hope it works as planned. Thank you for a great script!

Hey, thank you again. The import worked flawlesly and also found a host with this issue in the logs. Will tey to fix it the next few days.

Great contribution

**Comment by bb-Ricardo** [comment]
Hey, I just pushed a new commit to "development". Can you test it out and see if it works?

**Comment by SerhiiZahuba** [comment]
I have a successful test run, visually all virtual machines have been created

**Comment by danilutkin** [comment]
Seems it work fine with single Esxi hosts. Thanks a lot for your great script) Will use the last version of it from development branch and if it go wrong will text it.

**Comment by bb-Ricardo** [comment]
Thank you for all the feedback. I will close this issue for now so I can finally bush out the 1.3.0 release.

If you still encounter issue then please don't hesitate to open a new issue.

Thank you

**Comment by vacumet** [comment]
Except for a few duplicate IPs i have on a group of VMs which is a non-issue fo me, everything works!
Good job @bb-Ricardo

**Comment by bb-Ricardo** [comment]
Version `1.3.0` has just been released

**Comment by bb-Ricardo** [comment]
And thank you @vacumet again for the govc package. It helped a lot.

**Comment by vacumet** [comment]
> Version `1.3.0` has just been released

That's what i noticed and installed :)
