### ISSUE TITLE
Add netbox-sync to netbox-docker

### ISSUE THREAD

**Issue by nikolasj** [bb-Ricardo/netbox-sync#226]
Hi! Tell me please. How to add this plugin to [netbox-docker](https://github.com/netbox-community/netbox-docker) and run it how plugin.
Or do I need to separately only run on the cronjob?

**Comment by bb-Ricardo** [comment]
Hi, this is not a plugin for NetBox. You can run this as own instance in a docker container somewhere in your environment. It just needs network connection to all vCenter instances you want to sync and NetBox.

**Comment by nikolasj** [comment]
Thank you!
