### ISSUE TITLE
Not all IPs synced on one object

### ISSUE THREAD

**Issue by izheen** [bb-Ricardo/netbox-sync#23]
Hello!

We are having an issue with one virtual firewall that doesn't get all ip's synced in to Netbox. Checked the logs and have the following, what could be the issue?

2021-01-13 08:26:34,204 - ERROR: Problems resolving relation 'primary_ip4' for object 'fw00XX-dc0X-cp' and value '{'id': 285, 'url': 'https://netbox/api/ipam/ip-addresses/285/', 'family': 4, 'address': '172.16.103.1/24'}'

2021-01-13 08:26:34,307 - ERROR: Problems resolving relation 'primary_ip4' for object 'fw00XX-dc0X-cp' and value '{'id': 285, 'url': 'https://netbox/api/ipam/ip-addresses/285/', 'family': 4, 'address': '172.16.103.1/24'}'

**Comment by bb-Ricardo** [comment]
Hi,

can you delete the cache or disable the cache and try again?

**Comment by izheen** [comment]
stupid question but how do i do that :)?

**Comment by bb-Ricardo** [comment]
If installed in `/opt/netbox-sync` then you have a folder `cache`. Just delete the content. :D

**Comment by izheen** [comment]
Insert Shame Shame GoT gif.... Thanks :D ill try and get back to you!

**Comment by izheen** [comment]
Unfortunately still missing IPs on that vm there is however no more logs with the error from my first comment:

2021-01-13 10:21:18,677 - DEBUG2: Parsing vCenter VM: fw00XX-dcXX-cp
2021-01-13 10:21:18,869 - DEBUG2: Found a exact matching virtual machine object: fw00XX-dcXX-cp (vSAN-AF)
2021-01-13 10:21:18,869 - DEBUG2: Found a matching virtual machine object: fw00XX-dcXX-cp (vSAN-AF)
2021-01-13 10:21:18,869 - DEBUG2: Parsing 'virtual machine' data structure: fw00XX-dcXX-cp
2021-01-13 10:21:18,877 - DEBUG2: Found '3' NICs in Netbox for 'fw00XX-dcXX-cp'
2021-01-13 10:21:18,877 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (pubcustnet1-XX-vsan-af) (fw00XX-dcXX-cp)
2021-01-13 10:21:18,924 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 2 (cpdrifthasync-vsan-af) (fw00XX-dcXX-cp)
2021-01-13 10:21:18,924 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 3 (cpdriftvltrk-vsan-af) (fw00XX-dcXX-cp)
2021-01-13 10:25:46,629 - DEBUG2: Parsing vCenter VM: fw00XX-dcXX-cp
2021-01-13 10:25:46,807 - DEBUG2: Found a exact matching virtual machine object: fw00XX-dcXX-cp (vSAN-AF)
2021-01-13 10:25:46,807 - DEBUG2: Found a matching virtual machine object: fw00XX-dcXX-cp (vSAN-AF)
2021-01-13 10:25:46,807 - DEBUG2: Parsing 'virtual machine' data structure: fw00XX-dcXX-cp
2021-01-13 10:25:46,816 - DEBUG2: Found '3' NICs in Netbox for 'fw00XX-dcXX-cp'
2021-01-13 10:25:46,816 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 1 (pubcustnet1-250-vsan-af) (fw00XX-dcXX-cp)
2021-01-13 10:25:46,863 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 2 (cpdrifthasync-vsan-af) (fw00XX-dcXX-cp)
2021-01-13 10:25:46,863 - DEBUG2: Parsing 'virtual machine interface' data structure: vNIC 3 (cpdriftvltrk-vsan-af) (fw00XX-dcXX-cp)

I only have this regarding the LAN IP:

2021-01-13 14:26:13,163 - DEBUG2: Found default IPv4 gateway 172.16.103.1

**Comment by bb-Ricardo** [comment]
Is the interface IP currently assigned to a different machine? And it's their primary IP?

**Comment by izheen** [comment]
Noep, no results when search netbox for it.

**Comment by izheen** [comment]
it has quite alot of IPs this VM if thats of importance. It has 19 in total with ipv6 included(which we dont sync to netbox). But only one LAN IP gets synced, all(5) of the public IPs get synced tho.

**Comment by bb-Ricardo** [comment]
Are these IPs assigned to virtual interfaces inside the VM?

**Comment by izheen** [comment]
The firewall has three interfaces in VMWare, WAN, HA Sync and one for LAN. The LAN interface is a VLAN trunk in VMWare and inside the vm there is VLAN interfaces. The VM has VMWare tools so all IPs can be seen on the VM Pane in vCenter.

Ill try debug3 and vm_include_filter and get back to you, thank you so much!

**Comment by izheen** [comment]
Do i need to do something else than setting the vm_include_filter? Getting sooo much output with Debug3

**Comment by izheen** [comment]
` (vim.vm.GuestInfo.NicInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         network = 'XXvltrk-vsan-af',
         ipAddress = (str) [
            '172.16.103.1',
            'fe80::250:56ff:fe81:6f75'
         ],
         macAddress = '00:XX:XX:XX:XX:XX',
         connected = true,
         deviceConfigId = XXXX,
         dnsConfig = <unset>,
         ipConfig = (vim.net.IpConfigInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            ipAddress = (vim.net.IpConfigInfo.IpAddress) [
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '172.16.103.1',
                  prefixLength = 24,
                  origin = <unset>,
                  state = 'preferred',
                  lifetime = <unset>
               },`

This is one of the IPs that dont get synced, i see it in the debug log but there is so much info, any pointers on what to look for? 360mb log :D

**Comment by bb-Ricardo** [comment]
Only IP adresses assigned direcly to a VM device are synced. Check the interface MAC addresses for this VM in NetBox.

If the interface MAC of this IP does not match any of them then the IP is not synced. Then this is a virtual interface inside the VM and we cannot tell which VMWare interface is used for this IP. Therefore it will not be synced.

Can you check this?

**Comment by izheen** [comment]
I checked the MAC of the synced interface in Netbox, Matched it against the debug3 log and its the same mac for all the LAN IPs. However only one IP(192.168.111.1) is synced to netbox.

  (vim.vm.GuestInfo.NicInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         network = 'XXXvltrk-vsan-af',
         ipAddress = (str) [
            '172.16.103.1',
            'fe80::250:56ff:fe81:6f75'
         ],
         macAddress = '00:50:56:81:6f:XX',
         connected = true,
         deviceConfigId = XXXX,
         dnsConfig = <unset>,
         ipConfig = (vim.net.IpConfigInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            ipAddress = (vim.net.IpConfigInfo.IpAddress) [
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '172.16.103.1',
                  prefixLength = 24,
                  origin = <unset>,
                  state = 'preferred',
                  lifetime = <unset>
               },
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = 'fe80::250:56ff:fe81:6f75',
                  prefixLength = 64,
                  origin = <unset>,
                  state = 'unknown',
                  lifetime = <unset>
               }
            ],
            dhcp = <unset>,
            autoConfigurationEnabled = <unset>
         },
         netBIOSConfig = <unset>
      },
      (vim.vm.GuestInfo.NicInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         network = 'XXvltrk-vsan-af',
         ipAddress = (str) [
            '172.16.106.1',
            'fe80::250:56ff:fe81:6f75'
         ],
         macAddress = '00:50:56:81:6f:XX',
         connected = true,
         deviceConfigId = XXXX,
         dnsConfig = <unset>,
         ipConfig = (vim.net.IpConfigInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            ipAddress = (vim.net.IpConfigInfo.IpAddress) [
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '172.16.106.1',
                  prefixLength = 24,
                  origin = <unset>,
                  state = 'preferred',
                  lifetime = <unset>
               },
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = 'fe80::250:56ff:fe81:6f75',
                  prefixLength = 64,
                  origin = <unset>,
                  state = 'unknown',
                  lifetime = <unset>
               }
            ],
            dhcp = <unset>,
            autoConfigurationEnabled = <unset>
         },
         netBIOSConfig = <unset>
      },
      (vim.vm.GuestInfo.NicInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         network = 'XXvltrk-vsan-af',
         ipAddress = (str) [
            '172.16.107.1',
            'fe80::250:56ff:fe81:6f75'
         ],
         macAddress = '00:50:56:81:6f:XX',
         connected = true,
         deviceConfigId = XXXX,
         dnsConfig = <unset>,
         ipConfig = (vim.net.IpConfigInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            ipAddress = (vim.net.IpConfigInfo.IpAddress) [
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '172.16.107.1',
                  prefixLength = 24,
                  origin = <unset>,
                  state = 'preferred',
                  lifetime = <unset>
               },
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = 'fe80::250:56ff:fe81:6f75',
                  prefixLength = 64,
                  origin = <unset>,
                  state = 'unknown',
                  lifetime = <unset>
               }
            ],
            dhcp = <unset>,
            autoConfigurationEnabled = <unset>
         },
         netBIOSConfig = <unset>
      },
      (vim.vm.GuestInfo.NicInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         network = 'XXvltrk-vsan-af',
         ipAddress = (str) [
            '192.168.111.1',
            'fe80::250:56ff:fe81:6f75'
         ],
         macAddress = '00:50:56:81:6f:XX',
         connected = true,
         deviceConfigId = XXXX,
         dnsConfig = <unset>,
         ipConfig = (vim.net.IpConfigInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            ipAddress = (vim.net.IpConfigInfo.IpAddress) [
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = '192.168.111.1',
                  prefixLength = 24,
                  origin = <unset>,
                  state = 'preferred',
                  lifetime = <unset>
               },
               (vim.net.IpConfigInfo.IpAddress) {
                  dynamicType = <unset>,
                  dynamicProperty = (vmodl.DynamicProperty) [],
                  ipAddress = 'fe80::250:56ff:fe81:6f75',
                  prefixLength = 64,
                  origin = <unset>,
                  state = 'unknown',
                  lifetime = <unset>
               }

**Comment by bb-Ricardo** [comment]
Let's see. I will have a look at it later on.

**Comment by bb-Ricardo** [comment]
Can you add the full output of `DEBUG2` for this VM (XXX private data)?

The actual code is this:
https://github.com/bb-Ricardo/netbox-sync/blob/47c46f5a508e700a04cc16984589885cb52f051c/module/sources/vmware/connection.py#L2082-L2089

every IP address found on this interface is added as long as it passes the filter:
https://github.com/bb-Ricardo/netbox-sync/blob/47c46f5a508e700a04cc16984589885cb52f051c/module/common/support.py#L83-L112

And if any filter dismisses the address, there should be a log entry.

Then the IP is added to the inventory here:
https://github.com/bb-Ricardo/netbox-sync/blob/47c46f5a508e700a04cc16984589885cb52f051c/module/sources/vmware/connection.py#L1088-L1172

**Comment by izheen** [comment]
Sorry for the delay, can i send you this log unfiltered(only the logs for the vm ofc) somewhere? Since there are public ips and more in it. An email perhaps?

**Comment by bb-Ricardo** [comment]
Of course. Check the code. There is my mail address right in there.

**Comment by izheen** [comment]
Sent, thank you!

**Comment by bb-Ricardo** [comment]
Changed, tested, fixed, closed

**Comment by bb-Ricardo** [comment]
Changed, tested, fixed, closed
