### ISSUE TITLE
FHRP Netbox object has malformed api_path 

### ISSUE THREAD

**Issue by oddbodperkins** [bb-Ricardo/netbox-sync#233]
There's an erroneous '/' at the begining of the api_path value, causing failures:

Wrong:
api_path = "/ipam/fhrp-groups"

Correct:
api_path = "ipam/fhrp-groups"

Current errors:

ERROR: NetBox returned: GET /api//ipam/fhrp-groups/?limit=200&exclude=config_context Not Found

https://github.com/bb-Ricardo/netbox-sync/blob/6b31cd4dd9d2d5e2754818b48e46cc5d07bd482a/module/netbox/object_classes.py#L1702

**Comment by bb-Ricardo** [comment]
Ahh, good point. Thank you for reporting. Will fix it in the next release.

**Comment by bb-Ricardo** [comment]
Just fixt in `development` branch.
