### ISSUE TITLE
[Feature Request] Add support for vm <=> cluster device link

### ISSUE THREAD

**Issue by n-rodriguez** [bb-Ricardo/netbox-sync#235]
Hi there!

Do you think it's possible to add support for this feature : https://github.com/netbox-community/netbox/issues/8222 ?

My first use case is "to show where a VM (should be, or used to be) running".

Thank you!

**Comment by bb-Ricardo** [comment]
Hi,

This seems doable. Didn't even notice vm had a new attribute device 😄 .

**Comment by bb-Ricardo** [comment]
added a new config option `track_vm_host` to the `development` branch. Can you try it out and let me know if it works?

**Comment by n-rodriguez** [comment]
> added a new config option `track_vm_host` to the `development` branch. Can you try it out and let me know if it works?

It works! Thank you!
