### ISSUE TITLE
virtual machines are not removed from netbox

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#25]
I deleted several virtual machines from vcenter, started synchronization, but after synchronization the virtual machines remained in the netbox off. What information do you need to provide to help solve problems?

**Comment by bb-Ricardo** [comment]
Just check the docu and your tags in NetBox. You have a pruning_delay_in_days setting. If you want the sync script to delete everything immediately then just that this option to 0.

**Comment by SerhiiZahuba** [comment]
Thank you. I put 0 on this line but they didn't get deleted. Only when I started it for the third time - everything was gone. Thanks again

**Comment by bb-Ricardo** [comment]
This is still a problem witch caching. You can switch it of and see if syncing works better. If your NetBox instance is fast enough then you don't really need caching.

Try setting `use_caching` to `false`.
