### ISSUE TITLE
Issue with HA servers

### ISSUE THREAD

**Issue by hyggja** [bb-Ricardo/netbox-sync#250]
When netbox-sync runs, it generates warnings for these specific devices that share common IPs...

```WARNING: Current interface 'vNIC 1 (VLAN-Name) (VMName)' for IP 'aaa.bbb.ccc.ddd/32' and this one 'vNIC 1 (VLAN-Name) (VMName)' are both enabled. IP assignment skipped because it is unclear which one is the correct one!```

I realize it's only a warning, but whenever I see it I am forced to wonder if there's something I've set wrong within netbox/netbox-sync that is causing the sync to throw these warnings. 

------------------------

I have two different environments causing this scenario. One is with HAProxy and the other with ucarp.

In the first environment we have 4 IPs for node A / B / C. At any one time one of them can be running as the primary on IP 192.168.1. 1 with the others running as replication (always assigned to .2/.3/.4). If the current node acting as primary (on .1) experiences any issues, we fail over to one of the secondary nodes and it gains the primary IP. We see warnings generated when these IPs swap.

In the second environment we have a basic load balancer. Requests go into IP A, and are redirected to Node A or B (on IP B and C). Whenever we sync we see warnings if the loadbalancer sends us to a different node. 

------------------------

I'm hoping there's a way to set this in netbox so the warnings aren't generated (perfectionist). 

If there isn't a config for this, I'm hoping there is a way we can **exclude** individual addresses from the sync process. I know I could do this via the permitted subnets section of settings.ini, but... we have a LOT of IP addresses and configuring this would be much cleaner if there was an exclude option.

**Comment by bb-Ricardo** [comment]
Hi,

Excluding single addresses or subnets is implemented but documented in the "wrong" place as I just have seen:
https://github.com/bb-Ricardo/netbox-sync/blob/61d60db9afa8a565d0d4ab4202cb815c96bacb06/module/sources/vmware/connection.py#L243-L259

By this commit: https://github.com/bb-Ricardo/netbox-sync/commit/8e410a41a28622d281809cd9f958f3111f8f72fe

and here: https://github.com/bb-Ricardo/netbox-sync/blob/61d60db9afa8a565d0d4ab4202cb815c96bacb06/settings-example.ini#L330-L333

Just give it a try and see if this works for you.

**Comment by bb-Ricardo** [comment]
this issue has been fixed with commit 9953a8f3a7213f99985dbbe2879c88f4b90126e3
