### ISSUE TITLE
Tagging of unsupported netbox objects?

### ISSUE THREAD

**Issue by Apfelwurm** [bb-Ricardo/netbox-sync#253]
Hey, we have implemented netbox-sync and we get a lot of the following messages (with various Platforms, Manufacturers, and the clusters) on every run:

```
INFO: Platform 'Debian GNU/Linux 10 (64-bit)' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: vcenter01']'
INFO: Manufacturer 'Dell' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: vcenter01']'
INFO: Cluster type 'VMware ESXi' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: vcenter01']'
INFO: Cluster group 'Main Cluster' attribute 'tags' changed from '[]' to '['NetBox-synced', 'Source: vcenter01']'
```

If i'm not mistaken those objects don't support tags in the netbox data model, so maybe they should be excluded from the tagging?

**Comment by bb-Ricardo** [comment]
Hi @Apfelwurm,

which version of NetBox are you using?

NetBox 3.3.X supports tags for:
* /dcim/platforms/
* /dcim/manufacturers/
* /virtualization/cluster-types/
* virtualization/cluster-groups/

You can check it here: https://demo.netbox.dev/api/docs/

**Comment by bb-Ricardo** [comment]
Hi,

Any updates on that?

**Comment by Apfelwurm** [comment]
Hi @bb-Ricardo, thanks for your fast reply!
Seems like our automatic update broke and therfore we are currently on 3.0.11, so this is expected.
Sorry for the false error report and thanks for pointing that out :D

**Comment by bb-Ricardo** [comment]
> Hi @bb-Ricardo, thanks for your fast reply! Seems like our automatic update broke and therfore we are currently on 3.0.11, so this is expected. Sorry for the false error report and thanks for pointing that out :D

No worries, thanks for getting back
