### ISSUE TITLE
Allow changing of location for cache

### ISSUE THREAD

**Issue by Eldiabolo21** [bb-Ricardo/netbox-sync#254]
Hi Ricardo! 

I'm currently trying to containerize netbox-sync with check-redfish. One of the (smaller) problems right now is, that netbox-sync will lose it's cache when the container gets recreated, making it take forever. 

I clone the repo in the docker file and since netbox-sync creates the cache directory in the git folder, I cant mount the cache folder some where else. 

A simple config option to place the cache folder else where would be great!

**Comment by bb-Ricardo** [comment]
Hi,

Good idea, will try to add that.

**Comment by bb-Ricardo** [comment]
just pushed a change which adds this config option

**Comment by Eldiabolo21** [comment]
This looks great, but if I run with latest commit i run again into the bug I mentioned in #203
