### ISSUE TITLE
Do not set MTU size on vNIC of VM

### ISSUE THREAD

**Issue by Houtek** [bb-Ricardo/netbox-sync#261]
Hi,
is it somehow possible to not set the MTU size on a vNIC? 
Netbox-sync grabs the MTU size from the vSwitch, when I'm not completely wrong. 
We have a different MTU setting in the VM (1500), which often is not the same as on the vSwitch (9000).

**Comment by bb-Ricardo** [comment]
Hi,

currently it I not possible to switch this setting on and off.

Would it help to add a config setting to disable this functionality?

This setting would apply for the whole configured vCenter.

**Comment by Houtek** [comment]
Hi, 
yes, a setting in the config would be good. Already searched where I can put it, but didn't find the part.

**Comment by bb-Ricardo** [comment]
Hi,

just pushed a commit to the development branch. Can you check it out and test if this solves your issue?

**Comment by Houtek** [comment]
Hi,
this seems to work.
Thank you.

**Comment by bb-Ricardo** [comment]
Great, thank you for testing it. Hope to release the new version soon.
