### ISSUE TITLE
VLAN Exclusion

### ISSUE THREAD

**Issue by jan-hagen** [bb-Ricardo/netbox-sync#266]
Hi,

Is it possible to exclude some VLAN's from the sync to Netbox?
We do have a trunk VLAN (0-4094) to scan the traffic of the VLAN's, but we don't want to have all of these 4094 VLAN's separately configured in Netbox.

Thanks for your help.

**Comment by pdenessen** [comment]
I would say to assign a TAG to the VLANs you want to sync.

**Comment by bb-Ricardo** [comment]
Hi,

I think this was already requested at some point.

You have a valid use case which would create pretty much every VLAN in NetBox which is not desired. [NetBox also does not support VLAN pools](https://github.com/netbox-community/netbox/issues/3251).

We discussed adding a config option to exclude VLANs but it is really hard to come up with a possible notation for excluded VLANs.

Some people want:
* exclude by ID
* exclude by ID and site
* or exclude globally
* or exclude by VLAN name or
* by regex on plan name
* and/or site
* or a certain range

There are too many possibilities of excluding or including that it currently is only possible to enable or disable VLAN sync for the whole source.

What are your thoughts on this?

**Comment by jan-hagen** [comment]
Thank you for your fast reply!

In our Case we would like to exclude them by a regex of the name.
I think if it would be possible to do it like that or based on the ID it would sufficient.

Maybe it could also be practical to set a TAG for the VLAN's you don't want to sync, so you don't have to tag a whole lot of VLAN's.

What do you think about this?

**Comment by bb-Ricardo** [comment]
Hi @jan-hagen,

In my opinion tags are possible but maybe not the best solution. You would need to add the VLAN to NetBox first, before the first run and tag this VLAN accordingly.

I might add two config options:
* one to exclude by name (Site could also be included here, probably)
* and one to exclude by id

**Comment by jan-hagen** [comment]
Hi @bb-Ricardo 

I agree, that wouldn't be a good solution, but I thought about Tags in Vcenter not in Netbox.
But if you could integrate the other two options that would be enough I think, or at least for my case.

Thank you very much!

**Comment by bb-Ricardo** [comment]
Would do it in the next release. Just trying to solve the last two known bugs and then start working on the next one.

**Comment by bb-Ricardo** [comment]
Hey @jan-hagen,

I just pushed a new commit which adds this functionality. Can you please checkout the `development` branch and test ist?

https://github.com/bb-Ricardo/netbox-sync/blob/d1db0d0aaf87cdf7bd036c1cc20ad312827acddc/settings-example.ini#L321-L330

Thank you

**Comment by jan-hagen** [comment]
> Hey @jan-hagen,
> 
> I just pushed a new commit which adds this functionality. Can you please checkout the `development` branch and test ist?
> 
> https://github.com/bb-Ricardo/netbox-sync/blob/d1db0d0aaf87cdf7bd036c1cc20ad312827acddc/settings-example.ini#L321-L330
> 
> Thank you

Hey @bb-Ricardo,

Thank you, I will do this asap!

**Comment by jan-hagen** [comment]
Hi @bb-Ricardo 

I tried it out and confirm that i works with the regex I use.

Thank you very much.
I think we can close this Issue.

**Comment by bb-Ricardo** [comment]
Hi, thank you for testing it out. Will be in the next version.
