### ISSUE TITLE
Sync Device interface with FC

### ISSUE THREAD

**Issue by juliouzzzz** [bb-Ricardo/netbox-sync#269]
Hello,

Is there a way or a new feature to sync Fiberchannel interfaces with WWNN to ESXi devices ?
Because when i manualy add fc interfaces on devices they are erased or replace by NET interfaces 
If i add my interfaces before first sync they are "mixed" with net interfaces (example : Name, mac changed, but WWNN and cable stayed)

thanks
Julien

**Comment by bb-Ricardo** [comment]
any updates?

**Comment by bb-Ricardo** [comment]
closing this issue due to no response
