### ISSUE TITLE
IP prefix length warning

### ISSUE THREAD

**Issue by gstorme** [bb-Ricardo/netbox-sync#27]
Hi,

The docs mention this, and logs contain `WARNING: IP prefix length of 'x.x.x.x/32' (vNIC 1 (x_NFW_3814) (vm)) does not match network prefix length 'x.x.x.x/24'`

But the reported IP's for VMWare virtual machines do not include a subnet, so IP's collected from VMWare sources will always be /32, right? I don't think there is a way for pyvmomi to retrieve the subnet for the IP's of the vm's, or am I wrong?  
And as such, that warning will always be displayed.

**Comment by bb-Ricardo** [comment]
Hi.

The IP addresses are collected inside the VM by the VMWare guest tools. They even collect all the routes inside the VM. And also the subnet configured for each IP address. Yiu can see it in this log here: https://github.com/bb-Ricardo/netbox-sync/issues/23#issuecomment-760094058

There you can see the attribute 'prefixLength:24'

Can you check if the configured subnet inside your VM is correct or if the guest tools are up to date?

**Comment by gstorme** [comment]
Oh, nice.
It looks like this occurs on secondary IP addresses.
The subnet of the primary IP that is polled, is correct.
The subnet of secondary IP's that is polled, is not correct.

I've used the `community.vmware.vmware_guest_info` ansible module, which also uses pyvmomi, to collect the data from a VM.
The interface config of the VM:

```
    inet x.x.190.97/26 brd xxx.xx.190.127 scope global ens192
    inet x.x.190.114/26 brd xxx.xx.190.127 scope global secondary ens192:1
```

The data from pyvmomi:
```
                "net": [
                    {
                        "_vimtype": "vim.vm.GuestInfo.NicInfo",
                        "connected": true,
                        "deviceConfigId": 4000,
                        "dnsConfig": null,
                        "ipAddress": [
                            "xxx.xx.190.97",
                            "xxx.xx.190.114",
                            "fe80::250:56ff:fe97:3419"
                        ],
                        "ipConfig": {
                            "_vimtype": "vim.net.IpConfigInfo",
                            "autoConfigurationEnabled": null,
                            "dhcp": null,
                            "ipAddress": [
                                {
                                    "_vimtype": "vim.net.IpConfigInfo.IpAddress",
                                    "ipAddress": "xxx.xx.190.97",
                                    "lifetime": null,
                                    "origin": null,
                                    "prefixLength": 26,
                                    "state": "preferred"
                                },
                                {
                                    "_vimtype": "vim.net.IpConfigInfo.IpAddress",
                                    "ipAddress": "xxx.xx.190.114",
                                    "lifetime": null,
                                    "origin": null,
                                    "prefixLength": 32,
                                    "state": "preferred"
```

The VM is a Debian 10 with open-vm-tools 10.3.10.

**Comment by bb-Ricardo** [comment]
This looks like the spot where they are added: https://github.com/vmware/open-vm-tools/blob/d0b7c90917f4f2afcb0583988d58bc3ec75ad023/open-vm-tools/lib/nicInfo/nicInfo.c#L434

Otherwise can you open a issue for open-vm-tools?

**Comment by gstorme** [comment]
Looks like this is already fixed in a more recent version.
Tested on 11.1.5 and works fine there.

**Comment by bb-Ricardo** [comment]
Great to hear.
