### ISSUE TITLE
Vcenter custom attributes pruning

### ISSUE THREAD

**Issue by joshb89** [bb-Ricardo/netbox-sync#279]
There doesn't appear to be any options for custom field pruning. I added a new custom field in vmware and synced it to netbox without issues, but when I changed the name of the field in vmware and synced again, the original field stayed and a new one was created in netbox.

**Comment by bb-Ricardo** [comment]
Thank you

**Comment by bb-Ricardo** [comment]
Hey @joshb89,

I was just looking into this and it's not as easy as I thought.

Before you can assign a custom field and a value to an object you need to create the custom field in NetBox itself. Even though they are prefixed they can be used by one or more vCenters. Changing the name in one vCenter does not change it in all the vCenters which might use the same custom field. Only if the name is changed in all vCenters then it would be safe to remove.
The same applies for deleted custom attributes.

I know it sounds silly but a manual remove in NetBox would by far be the safest option.

What do you think?

**Comment by bb-Ricardo** [comment]
closing this due to no response
