### ISSUE TITLE
Duplicate MAC address between hosts in same cluster

### ISSUE THREAD

**Issue by UntestedEngineer** [bb-Ricardo/netbox-sync#280]
I am not sure how to get around this, however I have two hosts in the same cluster with the same interface MAC address.  Two of my servers have a "vusb0" interface with the same MAC address so only one host is added to Netbox due to the MAC overlap.  How can this be accommodated?

**Comment by bb-Ricardo** [comment]
Hi,

This is something that should not happen, but here we are. The only thing that comes to my mind is to add another config option to ignore interfaces with certain MAC addresses.

**Comment by UntestedEngineer** [comment]
Using the filter functions I implemented a basic check for host nic filter.  I guess if you really wanted to get down to the host(s) + pnic + MAC level you could but I wouldn't think this would be a common case?

### Added

**settings.ini**
`# This will include/exclude host pnics, useful if all hosts share a common pnic with a common mac address
host_nic_exclude_filter =
#host_nic_include_filter =`

**sources.vmware.connection.py**
settings = {
        **"host_nic_exclude_filter": None,
        "host_nic_include_filter": None,**
    }

        for pnic in grab(obj, "config.network.pnic", fallback=list()):

            pnic_name = grab(pnic, "device")
            pnic_key = grab(pnic, "key")

            _# include/exclude host pnics
            if self.passes_filter(pnic_name, self.host_nic_include_filter, self.host_nic_exclude_filter) is False:
                continue_     

`
Not sure if I can open pull requests.

**Comment by UntestedEngineer** [comment]
Using the filter functions I implemented a basic check for host nic filter. I guess if you really wanted to get down to the host(s) + pnic + MAC level you could but I wouldn't think this would be a common case?

### Added

**settings.ini**
```
# This will include/exclude host pnics, useful if all hosts share a common pnic with a common mac address
host_nic_exclude_filter =
#host_nic_include_filter =
```

**sources.vmware.conncetions.py**
```
    settings = {
        "host_nic_exclude_filter": None,
        "host_nic_include_filter": None,
     }

        pnic_data_dict = dict()
        for pnic in grab(obj, "config.network.pnic", fallback=list()):

            pnic_name = grab(pnic, "device")
            pnic_key = grab(pnic, "key")

            # include/exclude host pnics
            if self.passes_filter(pnic_name, self.host_nic_include_filter, self.host_nic_exclude_filter) is False:
                continue  
```

**Comment by bb-Ricardo** [comment]
Hey,

something similar can be added. Will have a look into it.

**Comment by mrcool1575** [comment]
I have the exact same problem with some Supermicro servers

**Comment by mrcool1575** [comment]
Perfect,

I Will test it tomorrow, when i get to work :)

**Comment by mrcool1575** [comment]
Works like a charm :)

**Comment by bb-Ricardo** [comment]
That's great to hear. Then I will conmsider this issue as resolved and close it.
