### ISSUE TITLE
How to backup config/data

### ISSUE THREAD

**Issue by 3bruno** [bb-Ricardo/netbox-sync#282]
Hi all.

When I backup the netbox database and move it to a new server and try to run netbox sync again (new installation), all items are marked as orphaned.

What is the best way to take advantage of previously collected data?

**Comment by bb-Ricardo** [comment]
Hi,

Did you try to delete the cache directory before the first sync to the newly restored NetBox instance?

**Comment by 3bruno** [comment]
Hi Ricardo. Yes and not worked. 

If I move the cache directory to the newly restored Netbox instance and use the same version was worked, but if I use a fresh install (without cache directory) or a different branch like development with or without cache directory not worked.

**Comment by bb-Ricardo** [comment]
closing due to no response
