### ISSUE TITLE
Did not get IP of VM that deploy automation via Ansible/Terraform

### ISSUE THREAD

**Issue by dauongdia2525** [bb-Ricardo/netbox-sync#283]
Hi Ricardo, My vcenter had a lot of virtual machines deployed via IAC tools like ansible and terraform.
I really that netbox did not get IP of those virtual machines, just get ip form virtual machines that deploy or clone manual.
Is there any custem to get ip from automate deploy virtual machines?
Have a nice day.
![lỗi netbox k ăn ip](https://user-images.githubusercontent.com/64430144/223696346-040e84d1-50a4-49f8-877d-8c5859b20889.PNG)

**Comment by bb-Ricardo** [comment]
Hi,

Most likely there are no vmware tools installed inside theses VMs. Or just a really old version.

Just try to install/update them for one VM and run another sync, then they should appear in NetBox.
