### ISSUE TITLE
Issue with config options  'overwrite_device/vm_interface_name' set to False on initial syncs

### ISSUE THREAD

**Issue by martinyardley** [bb-Ricardo/netbox-sync#287]
Hi,

I'm testing the Netbox sync script, importing to netbox from vSphere .  All apart from synchronizing the IP address to the virtual machine works fine (the host IP addresses update successfully). IP addresses are synchronized to IPAM. A http 400 bad request error is logged. 

I believe this has been logged before, however I have been unable to locate the solution.

![image](https://user-images.githubusercontent.com/128731135/227277262-3a5d5990-e1ce-4c9e-b19f-fbead107abfa.png)

![image](https://user-images.githubusercontent.com/128731135/227281952-144d4b29-9f34-4103-a349-1205d6cc6fca.png)

Any assistance would be greatly appreciated.

Thanks,
Martin

**Comment by bb-Ricardo** [comment]
Hi,

well, this is not meant to happen. Would it be possible to provide a full debug log?

**Comment by martinyardley** [comment]
Hi, 

Thanks for you fast response! Yes I have a clean log file from this morning, I have edited some confidential information.  Can I email it to you?

Thanks,

Martin

**Comment by bb-Ricardo** [comment]
Great, yes you can email it to me. If you call the script with `--help` you should se my mail address.

**Comment by martinyardley** [comment]
Hi,

Sorry, it's not displaying an email address...

![image](https://user-images.githubusercontent.com/128731135/227482819-8e1c300f-6353-47a0-9b0d-eb7d4a099b3f.png)

**Comment by bb-Ricardo** [comment]
Well, indeed. Sorry for that.

This should be better:
https://github.com/bb-Ricardo/netbox-sync/blob/20e3a3c2ff2925e9e88ff4dcb39d0c3c589d0d48/module/__init__.py#L12

**Comment by martinyardley** [comment]
Perfect, I've emailed you the log.  Thanks again!

**Comment by bb-Ricardo** [comment]
Hey @martinyardley,

would you be able to test this fix?

Best would be with a clean (not previously synced) NetBox database and the config option `overwrite_vm_interface_name` set to False.

Thank you

**Comment by martinyardley** [comment]
Hi Ricardo,  

I can't find an updated version of the script? I won't be able to run it against a "clean" DB just yet, as others are developing scripts and working on this system. The production netbox DB has not yet been updated with the netbox sync script - So I'll be able to test fully once I have the go ahead 

Cheers,

Martin

**Comment by bb-Ricardo** [comment]
Hi,

You just need to check out the "development" branch and run the script with the changed option again.

I guess, deleting all interfaces from a previously synced VM should trigger the same conditions.

And look for ERROR messages after the sync.

Thank you.

**Comment by Houtek** [comment]
Hi,
we have the same issue. I will test this in our environment.

Best,
Sascha
