### ISSUE TITLE
VM device not set if strip_host_domain_name = True

### ISSUE THREAD

**Issue by clementTal** [bb-Ricardo/netbox-sync#294]
If strip_host_domain_name is set to True, VM host are not set:

`ERROR: Unfortunately updated item device for object VM_NAME could not be fully resolved: <NBDevice instance HOST_NAME.bla.com' at XXXX>`

Everything if OK if strip_host_domain_name is set to False, but host name keep the domain name.

**Comment by bb-Ricardo** [comment]
Hi @clementTal,

This is indeed a bug and I pushed a fix to the `development` branch. Can you please check it out and test if this resolves your issue?

Thank you very much.

**Comment by clementTal** [comment]
Thanks !
Your fix worked perfectly
