### ISSUE TITLE
Unable to add VMs from Cluster located on two sites

### ISSUE THREAD

**Issue by smasharov** [bb-Ricardo/netbox-sync#301]
I have a big cluster located on two different sites with several hundreds VMs. Site field is now empty and it is impossible to set it because hosts are located on the different sites. The script tries to set site for the cluster, but get an error from Netbox and all further steps are also failed.

Is it possible to somehow leave the site of the cluster empty?

**Comment by bb-Ricardo** [comment]
Hey,

Have you tried creating a new site manually which represents both sites "virtual-site-a-and-side-b" and assign this via `cluster_side_relation`?

**Comment by smasharov** [comment]
Yes, but but dozens of physical servers already assigned to different sites and racks on these sites. And I got an error if I try to assign the cluster: "XX devices are assigned as hosts for this cluster but are not in site YY" 
If I try to change site of the server I get an error: "Rack AA does not belong to site YY"

So in my opinion the best way to leave the site of the Cluster empty in such cases

**Comment by bb-Ricardo** [comment]
Hhmmm, valid point, I probably can add a config option to disable the assignment of a site to the vm. But then the host tracking will not work. Fo you have host_tracking enabled?

**Comment by smasharov** [comment]
Thanks! I think this option will be good for the particular cluster in config. I have only one cluster like this, the others are located on the one site.

**Comment by IPFox** [comment]
Hi, we have similar issue and after some thought our proposal for this would be the following:
Clusters:
- use the cluster_site_relation parameter to map clusters that are multisite, our keyword MULTISITE
- modify the connectivity.py under get_site_name function by replacing the default with something like:
   if self.get_object_relation(object_name, relation_name) == "MULTISITE":
            site_name = None # or some similar keyword
        elif site_name is None:
            site_name = self.site_name
- then catch that on the NBCluster definition and set the site to empty for those multisite clusters, others should go as they do now.
VMs on the other hand, should get the site name from the hosts instead of clusters to keep tracking the actual location of the VMs.

Still looking which all the parts need to change to make this happen, so any help would be highly appreciated :)

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for this idea. I'm currently unsure if a cluster can have multiple sites. That way it should not matter if site is taken from host or cluster. Maxbe that changed in newer NetBox versions.

**Comment by IPFox** [comment]
Hi,

Yes it is possible to make cluster without site, composed from hosts on multiple sites.
Similar case was discussed on Netbox discussions as well sometime back: https://github.com/netbox-community/netbox/issues/1976

**Comment by worldworm** [comment]
Hi,
yes, you are right, that would no longer work.

I only have two more ideas 😃 
Either make it more specific. E.g. `netbox-sync-none`.
Or simply let the user define it himself and give a new option such as 
`none_site_identifier: NoSite`
`cluster_site_relation: Cluster_FFM.* = Frankfurt, Cluster_Shared = NoSite`

What do you think?

**Comment by bb-Ricardo** [comment]
I would suggest to use a special character and None.

Like:
- `<NONE>`
- `%NONE%`

What do you think?

**Comment by worldworm** [comment]
That's a great idea! I prefer `<NONE>`
The `%` look like some weird variables. 😆 

Pull request coming up #333

**Comment by bb-Ricardo** [comment]
Hey @smasharov  and @IPFox,

the pull request #333 has just been merged. You you be able to checkout development and test the changes. 

Thank you @worldworm for this PR.

**Comment by ahellsten** [comment]
Hi,

As per my initial testing this seems to be working as expected.

**Comment by smasharov** [comment]
thanks, I have finally tested it today and it works now as expected
