### ISSUE TITLE
DNS Reverse Lookup Not Working

### ISSUE THREAD

**Issue by muratbulat** [bb-Ricardo/netbox-sync#306]
Hi,

> dns_name_lookup = True
> custom_dns_servers = 10.48.6.11, 10.48.6.11

DNS lookup not working, aiodns and asyncio modules installed, netbox-sync.py working from .venv directory, i testing via lookup tool getting dns record from my DNS servers.

I checked DEBUG2 DEBUG3 log levels but i didn't saw any dns query or info.

Thanks.

**Comment by bb-Ricardo** [comment]
Hi,

Very difficult to help with this as I can only guess what is happening on your side.

It looks like you configured the same server twice. How does your command line to lookup up the dns record look like?

**Comment by muratbulat** [comment]
Sory, DNS servers was 10.48.6.10, 10.48.6.11
Example PTR query.

```
C:\Users\mb>nslookup 10.48.6.1
Server:  portainer.zion.local
Address:  10.48.6.51

Name:    bifrost.zion.local
Address:  10.48.6.1
```

**Comment by muratbulat** [comment]
Switch problem, disabled value control, worked.

```
dns_name_lookup = True
custom_dns_servers = 10.48.6.10, 10.48.6.11
```

```
        # iterate over all IP addresses and try to match them to a prefix
        for ip in self.get_all_items(NBIPAddress):

            # ignore IPs which are not handled by any source
            if ip.source is None:
                continue

            # get IP and prefix length
            ip_a = grab(ip, "data.address", fallback="").split("/")[0]
            log.debug("DDDNNNSSS 02")

            # check if we meant to look up DNS host name for this IP
            #if grab(ip, "source.dns_name_lookup", fallback=False) is True:

            if ip_lookup_dict.get(ip.source) is None:

                    ip_lookup_dict[ip.source] = {
                        "ips": list(),
                        "servers": grab(ip, "source.custom_dns_servers")
                    }

            ip_lookup_dict[ip.source].get("ips").append(ip_a)
            log.debug("DDDNNNSSS 04")
```

**Comment by bb-Ricardo** [comment]
Hi, like you had a ptoblem with a switch in your data center?

**Comment by muratbulat** [comment]
> Hi, like you had a ptoblem with a switch in your data center?

Hi, No, i think `dns_name_lookup = True` not working. This parameter still False in logic.

Thanks.

**Comment by bb-Ricardo** [comment]
Hi, that could actually be possible. From the code snipped you posted, I would not work with the recently changed config parsing.

I will have a look into it

**Comment by bb-Ricardo** [comment]
Hey @muratbulat,

I just pushed a new commit to the `development` branch. Can you have a look if it works now?

Thank you.

**Comment by muratbulat** [comment]
Hi @bb-Ricardo `development`  patch `3089543f31960ebf48520d39c95d0e573ed6ac64 ` working.

Thank you.

**Comment by bb-Ricardo** [comment]
Thanks for this fast testing.
