### ISSUE TITLE
[FR] Add power supplies as modules instead of inventory

### ISSUE THREAD

**Issue by pdenessen** [bb-Ricardo/netbox-sync#311]
Can you make an option to add the power supplies as modules to a device rather then adding them as inventory.
The device type has a couple of module bays defined as "Power supply" units.
The power supplies are defined as module-type and have a power-port.

I think the script should do the following:
1. Check if the PS should be added as inventory or as module.
2. If as module, check if the module-type is defined, if not create it
3. Check if the Device type has free module bays then add then add the power supplies to the respective module-bays and fill all related fields (serialnr etc)
5. If the module bays are not present then report an error
6. If the modules are present the overwrite them pending on a setting in the settings.ini file.

**Comment by pdenessen** [comment]
Hi @bb-Ricardo,

power supplies have indeed no interface but an power-port, weight, serial nr etc. Power units can (mostly) easily be replaced and therefore I believe to have them better listed as modules rather then inventory.
We also have defined module-types for the PCI-e cards where we add the interfaces to it. These will interfaces then be added to the main device and identified with help of the {module} parameter and slot position value of the the module-bay in the device.

Working with modules makes it easier to select predefined module-types and have them all the same identified. Something which is not possible with inventory where you can name them anything you want and lose consistency.

Hopes this helps else I am glad to provide some examples.

**Comment by bb-Ricardo** [comment]
This is highly dependend on the type of device. This means that netbox-sync needs to create different device types based on the model name.

Also a device has Power ports for exact that reason, at least that's what I thought they are for.

**Comment by bb-Ricardo** [comment]
Will close this is as it would blow the scope way out of proportion. Implementing each device type and their modules is currently not planned. Sorry.
