### ISSUE TITLE
Color of device role "Server" always changed back

### ISSUE THREAD

**Issue by patschi** [bb-Ricardo/netbox-sync#319]
I intended to use a different color for the generic device role "Server", but after running Netbox-Sync it always changed the color back. Looks like this is hardcoded here:
https://github.com/bb-Ricardo/netbox-sync/blob/3089543f31960ebf48520d39c95d0e573ed6ac64/module/sources/vmware/connection.py#L2401

Would be nice to use any customized color, or maybe prevent force-changing the color at all.

**Comment by bb-Ricardo** [comment]
Fixed in branch `development`, no more overwriting over Server role color for role `Server`
