### ISSUE TITLE
Incorrectly matching dedicated iLO interface found through redfish with vmk interface

### ISSUE THREAD

**Issue by pv2b** [bb-Ricardo/netbox-sync#330]
Hi!

I'm currently evaluating Netbox-Sync and I think I've found an issue with how the interface matching goes.

The issue I'm having is that when I have both vCenter and redfish enabled, it seems that the dedicated iLO interface is being incorrectly matched up with one of the virtual inerfaces (in my case vmk0) which causes netbox-sync to not properly sync. I end up with a "vmk0" itnerface with the MAC address and other properties of the dedicated iLO interface. This makes no sense, since vmk0 is a virtual interface, and the dedicated iLO interface is a compeltely unrelated physical interface.

Looking through the code, I think I can understand why, just from reading the comments (good job on those by the way, they were very helpful.) I quote:

```
        Try to match current object interfaces to discovered ones. This will be done
        by multiple approaches. Order as following listing whatever matches first will be chosen.

            by simple name:
                both interface names match exactly
            by MAC address separated by physical and virtual NICs:
                MAC address of interfaces match exactly, distinguish between physical and virtual interfaces
            by MAC regardless of interface type
                MAC address of interfaces match exactly, type of interface does not matter

            If there are interfaces which don't match at all then the unmatched interfaces will be
            matched 1:1. Sort both lists (unmatched current interfaces, unmatched new new interfaces)
            by name and assign them each other.

                eth0 > vNIC 1
                eth1 > vNIC 2
                ens1 > vNIC 3
                ...  > ...
```

It's this last rule, where the problem seems to occur. If we look at a snippet of some debug output:

```
2023-07-19 17:09:19,449 - DEBUG2: Found '17' NICs in NetBox for 'xxx.xxx.xxx.xxx'
2023-07-19 17:09:19,449 - DEBUG2: Found 1:1 MAC address match for physical NIC '1.1'
2023-07-19 17:09:19,450 - DEBUG2: Found 1:1 MAC address match for physical NIC '1.2'
2023-07-19 17:09:19,450 - DEBUG2: Found 1:1 MAC address match for physical NIC '2.1'
2023-07-19 17:09:19,450 - DEBUG2: Found 1:1 MAC address match for physical NIC '2.2'
2023-07-19 17:09:19,450 - DEBUG2: Found 1:1 MAC address match for physical NIC '3.1'
2023-07-19 17:09:19,451 - DEBUG2: Found 1:1 MAC address match for physical NIC '3.2'
2023-07-19 17:09:19,451 - DEBUG2: Found 1:1 MAC address match for physical NIC '3.3'
2023-07-19 17:09:19,451 - DEBUG2: Found 1:1 MAC address match for physical NIC '3.4'
2023-07-19 17:09:19,451 - DEBUG2: Found 1:1 MAC address match for physical NIC '4.1'
2023-07-19 17:09:19,452 - DEBUG2: Found 1:1 MAC address match for physical NIC '4.2'
2023-07-19 17:09:19,452 - DEBUG2: Matching 'Manager Dedicated Network Interface (1:1)' to NetBox Interface 'vmk0 (xxx.xxx.xxx.xxx)'
```

The last line is generated from here: https://github.com/bb-Ricardo/netbox-sync/blob/b9e236df43c463d4d09a8afeeb6d69f3f8ee62aa/module/sources/common/source_base.py#L168

And if we look where this is called, we can understand that we're currently in the call to add_device_vm_to_inventory from the redfish module namely here: https://github.com/bb-Ricardo/netbox-sync/blob/b9e236df43c463d4d09a8afeeb6d69f3f8ee62aa/module/sources/check_redfish/import_inventory.py#L788

So, Redfish will of course know about all the physical interfaces, this is logical, and will match them up with what's previously been discovered through the vCenter plugin by their MAC address, but then it will have some Netbox interfaces left over, namely the vmk ones. It will fall back to trying to match them by alphabetical sort of the interface name which will naturally match with vmk0. This is because the dedicated iLO interface is never discovered by the vCenter plugin, becuause that interface is not really an interface from ESXi's perspective.

In my own setup, I was able to stop this from happening by commenting out the code that does this type of last-resort matching, although I'm not quite sure if this is the correct fix, because I'm not sure what type of problem this last-resort match is actually trying to solve.

**Comment by bb-Ricardo** [comment]
Hi,

Yes this is a kind of draw back with the matching. Thumbs up for actually digging through the code and trying to solve the issue.

I could see two approaches here.

First: place the redfish source in the config above the vCenter source. So the redfish information is processed first and the MAC addresses will be correct.

Second: after the first run and the misalignment fix the MAC Addresses for the ILO and vmk0 manually and then the sync should work properly. But this would require at least one manual interaction for each new ESXi host.

The last resort matching is manly for VMs. Example:
* A VM mit interfaces is already present in NetBox.
* the interfaces named how they appear in the OS
* None of the interfaces has a MAC address assigned in NetBox (because admins are lazy)
* on first sync the VM is discovered and matched
* this way the Interfaces are assigned 1:1 in alphanumeric order
* 1. Interface of the VM is assigned to the first interface in NetBox and so on, ...

**Comment by bb-Ricardo** [comment]
Hi @pv2b,

same here. I fixed this in the latest `development` branch. Would you be able to check out it and see if this fixes your issue.

Thank you.

**Comment by bb-Ricardo** [comment]
will close this as resolved. Please open a new issue if a similar issue occurs again.
