### ISSUE TITLE
Redfish and vCenter modules fighting over descriptions

### ISSUE THREAD

**Issue by pv2b** [bb-Ricardo/netbox-sync#331]
So I have the same server being discovered both through redfish and through vCenter, and they end up fighting over the descriptions, leading to logs like this every time I run the program:

```
2023-07-19 17:41:36,834 - INFO: Interface 'vmnic0 (x.x.x.x)' attribute 'description' changed from '' to '1Gb/s  pNIC'
```

But nothing changed because later down (not logged), redfish source seems to change the description back to ''. Not sure how to get this to stop happening, I've not been able to find anywhere to prioritize the source of "description"?

**Comment by pv2b** [comment]
P.S. Setting `overwrite_interface_attributes = False` in the redfish source doesn't seem to fix this.

**Comment by bb-Ricardo** [comment]
Will have a look

**Comment by bb-Ricardo** [comment]
Hi @pv2b,

Sorry it took me so long to have a look into it.

I fixed this in the latest `development` branch. Can you try to check it out and see if it is working now?

Thank you

**Comment by bb-Ricardo** [comment]
will close this as resolved. Please open a new issue if a similar issue occurs again.
