### ISSUE TITLE
Don't change interface type if parent interface is defined

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/netbox-sync#332]
### Discussed in https://github.com/bb-Ricardo/netbox-sync/discussions/323

<div type='discussions-op-text'>

<sup>Originally posted by **dschartz** July  3, 2023</sup>

Hi, we are using Npar on our physical interfaces, So i define the Vmnic interfaces as child interfaces of our physically connected interfaces.

So for the moment the updates of the interfaces fails as setting the interface type is only permitted on non-child interfaces.
I there any possibility to check if interface pas a parent interface and ommit the Interface type change ? if not could you point me to the right spot to implement this check eventually ?

By the way, this is really an awesome tool</div>

**Comment by bb-Ricardo** [comment]
Hi @dschartz,

I added a fix for this issue. Can you please check out the development branch and test out if it now works for you? Thank you

**Comment by dschartz** [comment]
Hi Ricardo,I just tested your modification and it works like a charmLGDaniel SchartzOn 20 Jul 2023, at 22:54, Ricardo ***@***.***> wrote:﻿
Hi @dschartz,
I added a fix for this issue. Can you please check out the development branch and test out if it now works for you? Thank you

**Comment by bb-Ricardo** [comment]
great, thank you for testing. will close issue
