### ISSUE TITLE
adding esxi server harddisk information 

### ISSUE THREAD

**Issue by csetarun2** [bb-Ricardo/netbox-sync#334]
Team, 

 I did netsync for my esxi servers, Im getting cpu/memory info by default, but its not showing the disk related info, is there any way to add it ni custome fields.

![image](https://github.com/bb-Ricardo/netbox-sync/assets/21236859/1e9c99d8-8262-4a8e-b1eb-8e9a343d550f)

**Comment by bb-Ricardo** [comment]
Hi,

This is currently not implemented. I could recommend to have a look at https://github.com/bb-Ricardo/netbox-sync/blob/main/docs/source_check_redfish.md

**Comment by bb-Ricardo** [comment]
closing due to no response
