### ISSUE TITLE
NetBox-synced: Orphaned tag colour being reverted

### ISSUE THREAD

**Issue by Azmodeszer** [bb-Ricardo/netbox-sync#340]
The plugin always overwrites the auto-generated orphaned object tag colour with gray (607d8b) with each sync. Is this intentional? I'd like to give that particular tag a more prominent colour, so would be nice if it were allowed to survive. Changed colours already persist for other plugin-generated tags, but for some reason not this one.

**Comment by bb-Ricardo** [comment]
Hi, sorry, that is a bug. Will fix this in the next release.

**Comment by Azmodeszer** [comment]
Cheers

**Comment by bb-Ricardo** [comment]
Hey, just pushed a new commit to the development branch which should fix the issue.

would you be able to test it? thank you

**Comment by Azmodeszer** [comment]
Yes, just tested it and the colouring persists. Thank you!

**Comment by bb-Ricardo** [comment]
great, thank you for testing it
