### ISSUE TITLE
VLANs missing source tag

### ISSUE THREAD

**Issue by Azmodeszer** [bb-Ricardo/netbox-sync#349]
VLAN imports from vCenter are only tagged with "NetBox-synced", but not with a source tag like other objects. Why?

**Comment by bb-Ricardo** [comment]
Goood question.

**Comment by bb-Ricardo** [comment]
Hi @Azmodeszer,

I fixed this in the latest `development`  branch. Could you please check it out and test if it's working now?

**Comment by Azmodeszer** [comment]
Works.
