### ISSUE TITLE
tagging issue on objects from multiple vcenter sources

### ISSUE THREAD

**Issue by gstorme** [bb-Ricardo/netbox-sync#35]
Hi,

With multiple vcenter sources enabled, it seems the tagging only occurs for objects found in the first 3 sources in the settings.ini.
All objects from all vcenters are synced, however the tagging only occurs for objects from the first 3 vcenters.
This is both for the "Source: name" and the "Netbox-synced" tags.
The tag itself is created, but none of the objects from that source is tagged with it.

When simply moving a vcenter source up in the settings file, so it's one of the first 3 sources, the tagging does occur.

**Comment by bb-Ricardo** [comment]
any updates on that issue? any further findings?

**Comment by gstorme** [comment]
So far I think it's related to 1 specific vcenter that syncs 21.000+ items to netbox.
If this vcenter is enabled, tagging for items from the vcenters that are configured after that specific one, does not occur.
If I disable this vcenter or move it to the last one in the settings file, this does not happen.

But I still don't know why, haven't found any explanation for this in the logfile (ran with DEBUG2).

**Comment by bb-Ricardo** [comment]
21.000 objects wow. Stupid question. Is it possible that it runs out of memory or something?

**Comment by gstorme** [comment]
No OOM, and the sync script exits normally.
It's a pita to test this, cause the sync of that specific vcenter takes a lot of time :)
And your commit ebda6af266dffdfcbf4bb31f808edb6d39ba7f38 is a perfect workaround/solution for this, so for me this issue can be closed...

**Comment by bb-Ricardo** [comment]
ok, thank you
