### ISSUE TITLE
ini variable multi line

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#360]
Hello, tell me, I want to set the cluster_site_relation parameter, but the line is too long, I’m trying to wrap it to the next line, but for some reason the script ignores it and the default rule is immediately triggered another-server = .* = default_site

`cluster_site_relation = srv1 = site1, srv2 = site2, another-server = .* =  default_site`                        

```
cluster_site_relation = srv1 = site1, \
                        srv2 = site2, \
                        another-server = .* = default_site
```

**Comment by bb-Ricardo** [comment]
Hi,

the statement `another-server = .* = default_site` looks strange.

**Comment by Sivolen** [comment]
> Hi,
> 
> the statement `another-server = .* = default_site` looks strange.

this is my mistake when I wrote the issues, in fact it looks like this
```
cluster_site_relation = mak-upr-srv01.mzso.local = mak-stite, \
                                   anv-upr-srv01.mzso.local = anv-site, \
                                   ys-srv02.mzso.local = "ys-site1, test", \
                                  .* = YS-COD
```

**Comment by bb-Ricardo** [comment]
Hi,

Did you try to set it to this:
```ini
cluster_site_relation = ^mak-upr-srv01.local$ = mak-site, \
                        ^anv-upr-srv01.local$ = anv-site, \
                        ^ys-srv02.local$ = "ys-site1, test", \
                        .* = YS-COD

Cheers Ricardo

**Comment by Sivolen** [comment]
> Hi,
> 
> Did you try to set it to this:
> 
> ```ini
> cluster_site_relation = ^mak-upr-srv01.local$ = mak-site, \
>                         ^anv-upr-srv01.local$ = anv-site, \
>                         ^ys-srv02.local$ = "ys-site1, test", \
>                         .* = YS-COD
> 
> Cheers Ricardo
> ```

Looks like it doesn't work that way either.
```
cluster_site_relation = ^mak-upr-srv01.mzso.local$ = mkr-site, \
                        ^anv-upr-srv01.mzso.local$ =  anv-site, \
                        .* = YZH-KPR32-COD


```
It looks like it doesn’t work like that either, the first mkr cluster works, but the next ones don’t

```
2023-12-05 15:39:26,908 - ERROR: NetBox returned body: {'cluster': ['The selected cluster (anv-upr-srv01.mzso.local) is not assigned to this site (DC-SRG3).']}
```

**Comment by bb-Ricardo** [comment]
ping
