### ISSUE TITLE
Ignore guest os after initial seed

### ISSUE THREAD

**Issue by lwhitworth** [bb-Ricardo/netbox-sync#362]
We run a lot of Ubuntu VMs and would like to have them separated in Netbox by version as their platform, however when we run sync it takes the good old vmware default of "Ubuntu Linux (64-Bit)". 

![image](https://github.com/bb-Ricardo/netbox-sync/assets/4669414/6c255a46-1964-4193-b710-88c93daca6e8)

We have an ansible script that will change the platform for the hosts back, but the next time sync runs it will set it back to "Ubuntu Linux (64-Bit)".

Is there some way to add logic to say not to overwrite platform after initial creation?  Or something smarter I'm missing?

**Comment by gstorme** [comment]
Take a look at https://github.com/bb-Ricardo/netbox-sync/blob/main/settings-example.ini#L208

**Comment by lwhitworth** [comment]
@gstorme I looked into that, but that wouldn't help I don't think, as vmware is only ever going to return "Ubuntu Linux (64-Bit)" no matter the version, so I can't see how you'd then split that down further.......

**Comment by bb-Ricardo** [comment]
Hey @lwhitworth 

So you pretty much need an option to not overwrite the VM platform if it's already defined?

Unfortunately we rely on thw VMWare tools to provide the VM OS name and it seems like that's to much to ask to read info on that from `/etc/os-release`.

Should be not to difficult to add an option to avoid overwriting the platform. Currently it's more difficult to find the timw to work on it 🫤

**Comment by lwhitworth** [comment]
Yeah that's pretty much the long and the short of it cheers.  I have a workaround for now, so not hugely urgent.

**Comment by bb-Ricardo** [comment]
Hi @lwhitworth,

I just pushed a commit two new config options to the development branch?:
```diff
diff --git a/settings-example.ini b/settings-example.ini
index d00fb4f..cebe456 100644
--- a/settings-example.ini
+++ b/settings-example.ini
@@ -344,6 +344,13 @@ password = super-secret
 ; NetBox. The interface will only be matched by identical MAC address
 ;overwrite_vm_interface_name = True

+; define if the platform of the device discovered overwrites the device platform in
+; NetBox.
+;overwrite_device_platform = True
+
+; define if the platform of the VM discovered overwrites the VM platform in NetBox.
+;overwrite_vm_platform = True
+
 ; set a matching value for ESXi host management interface description (case insensitive,
 ; comma separated). Used to figure out the ESXi primary IP address
 ;host_management_interface_match = management, mgmt
 ```

Can you have a look at it and test it. If it works you are free to close this issue as resolved.

Thank you

**Comment by lwhitworth** [comment]
My man!  Great stuff, works perfectly.  Much appreciated.
