### ISSUE TITLE
Add support for Virtual disks introduced in Netbox 3.7

### ISSUE THREAD

**Issue by smasharov** [bb-Ricardo/netbox-sync#364]
New version of Netbox supports several virtual disks per VM

**Comment by bb-Ricardo** [comment]
Hi, yes I have seen this feature in the announcement. Would like to support this as well. But I'm using a helm chart for my test environment and currently stuck with 3.5.9 cause the author does not update it. Let's see If I get it to work

**Comment by bb-Ricardo** [comment]
great, now having 3.7.1 up and running.

Will look into supporting the new virtual disk components

**Comment by bb-Ricardo** [comment]
Hi @smasharov, @patschi, @vacumet,

I just added the support to the latest `development` branch. Can you please check it out and see if it works for you?

Thank you

**Comment by patschi** [comment]
Thank you so much, Ricardo!

It seems to work fine in my environment:

![image](https://github.com/bb-Ricardo/netbox-sync/assets/2029878/787b5f55-fdf9-4452-ab5e-9ca150b4c71a)
![image](https://github.com/bb-Ricardo/netbox-sync/assets/2029878/9309d895-b4b7-4aa2-aaf1-e8d30f000cbb)

**Comment by smasharov** [comment]
It works, but if the disk size is less than 1Gb it creates it with zero size.
Maybe it is worth to set them as the minimal 1Gb in such cases? I think the size should be rounded up all the times.

**Comment by bb-Ricardo** [comment]
Hi, great that it works, Valid point regarding the size. Will try to set it to 1 GB and also add the actual size to the description

**Comment by patschi** [comment]
I just had two thoughts:
1. I don't like the wording `Independent_persistent`, it looks a bit off. Maybe `Independent-Persistent` or so.
2. It would be nice to have the assigned Storage Policy of the individual disk added to the description.

**Comment by bb-Ricardo** [comment]
Do you have an example of independent persistant?

**Comment by patschi** [comment]
Here:
![image](https://github.com/bb-Ricardo/netbox-sync/assets/2029878/c0ed0ef9-8781-46dc-9799-24b91bda301c)

Just looks a bit off, IMHO.

**Comment by bb-Ricardo** [comment]
Ahh, thank you. This comes straight from the vCenter API. I could change it to look a bit nicer. Thanks for the hint.

**Comment by bb-Ricardo** [comment]
Hi,

just pushed another commit with the improved description.

I tried to find Storage Policy of the virtual disk but it seems you need an additional connection to the 'VMware Storage Policy Server' to query this information. I'm currently using vcsim for my test environment and this seems not supported.

**Comment by patschi** [comment]
I see. Okay. I just saw the Virtual Disk object in netbox do also have tags support. It would be a general awesome feature if Storage Policies might be applied to disk objects with the name of the storage policy. That would be great to sort/filter. (e.g. any VMs running on vSAN using RAID-1, etc)

But that's probably opening another can of worms in terms of integration. I can test scripts or whatsoever on my vCenter, if that helps.

**Comment by bb-Ricardo** [comment]
Would be great if we could close this issue and open a separate one for the storage policy.
