### ISSUE TITLE
Issue with ilo6 and/or server without storage controller

### ISSUE THREAD

**Issue by Guilh3m** [bb-Ricardo/netbox-sync#374]
Hello,

I'm having an issue syncing redfish source with newly acquired hpe 385 gen11 server without storage controller, only nvme disks.

Script crashing with this error :
```
Traceback (most recent call last):
  File "/opt/netbox-sync/netbox-sync.py", line 146, in <module>
    main()
  File "/opt/netbox-sync/netbox-sync.py", line 111, in main
    source.apply()
  File "/opt/netbox-sync/module/sources/check_redfish/import_inventory.py", line 151, in apply
    self.update_storage_controller()
  File "/opt/netbox-sync/module/sources/check_redfish/import_inventory.py", line 608, in update_storage_controller
    self.update_all_items(items)
  File "/opt/netbox-sync/module/sources/check_redfish/import_inventory.py", line 946, in update_all_items
    unmatched_inventory_items.sort(key=lambda x: x.get("full_name"))
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
In the json file i can see this in meta data : 
```
"data_retrieval_issues": {
            "storage_controller": [
                "No array controller data returned for API URL '/redfish/v1/Systems/1//SmartStorage/ArrayControllers?$expand=.'"
            ]
        },
```
Thank you

**Comment by bb-Ricardo** [comment]
Thank you for this issue,

will have a look at it.

**Comment by bb-Ricardo** [comment]
Hi @Guilh3m,

would you be able to send me an example inventory file where this is happening?

thank you

**Comment by Guilh3m** [comment]
De: "Ricardo" ***@***.***> 
À: "bb-Ricardo/netbox-sync" ***@***.***> 
Cc: "Guilh3m" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 14 Mai 2024 22:47:32 
Objet: Re: [bb-Ricardo/netbox-sync] Issue with ilo6 and/or server without storage controller (Issue #374) 





Hi [ https://github.com/Guilh3m | @Guilh3m ] , 

would you be able to send me an example inventory file where this is happening? 

thank you

**Comment by Guilh3m** [comment]
[192.168.101.11.json](https://github.com/bb-Ricardo/netbox-sync/files/15336020/192.168.101.11.json)

**Comment by bb-Ricardo** [comment]
@Guilh3m,

Thank you for the provided inventory file. I was able to fix the issue in the latest development branch.

can you try it out and see if it is fixed for you as well, please?

**Comment by Guilh3m** [comment]
Hello, tested development branch with success, synchronization working fine now.

**Comment by bb-Ricardo** [comment]
great, thank you very much for the verification. This will be part of the next release.
