### ISSUE TITLE
Cron job error

### ISSUE THREAD

**Issue by ipatsiotis303** [bb-Ricardo/netbox-sync#376]
Hello,

I face an issue when I try to set up the cron job. The errors are regarding the api_token and host_fqdn config options. These options are not empty in each configuration file I have created.

2024-03-04 20:41:26,406 - INFO: Starting NetBox Sync v1.5.1 (2023-09-25)
2024-03-04 20:41:26,406 - ERROR: Config option 'api_token' in 'netbox' can't be empty/undefined
2024-03-04 20:41:26,406 - ERROR: Config option 'host_fqdn' in 'netbox' can't be empty/undefined
2024-03-04 20:41:26,406 - ERROR: Config validation failed. Exit!

Everything work as expected when I manually trigger the configuration files through the virtual environment:
(.venv) [XXXX@netbox netbox-sync]# /opt/netbox-sync/netbox-sync.py -c settings-XXXX-XXXX.ini

**Comment by bb-Ricardo** [comment]
Hi,

Do you also use your virtual environment in your ceon job?

**Comment by bb-Ricardo** [comment]
Can you try to define the log file as a command option `-c`? Or set the log level to DEBUG2?

**Comment by ipats86** [comment]
Hello,
Thanks again for your awesome netbox-sync plugin. I manage to overcome the Erros by executing the following bash script in the cronjob.

#!/bin/bash
cd /opt/netbox-sync/
. .venv/bin/activate
/opt/netbox-sync/netbox-sync.py -c settings-XXXX.ini > /tmp/cron-debug-XXXX.log
exit 0

**Comment by bb-Ricardo** [comment]
Great that you foond a solution and that it helps you in your infrastructure needs.
