### ISSUE TITLE
allow partial sync with source orphaned logic

### ISSUE THREAD

**Issue by gstorme** [bb-Ricardo/netbox-sync#38]
Would it be possible to tag objects as Orphaned, only when the source is being actively polled, and not if the source is defined but set as `ènabled = false`?
This would allow for a custom sync schedule on a per-vcenter(s) base.

For example if you sync from 8 vcenters (vcenter1 to vcenter8), and you want to (temporarily) disable sync from vcenter7 and vcenter8 by setting `enabled = false`.
Right now, all of the objects that were synced from those two vcenters would get tagged as Orphaned.

**Comment by bb-Ricardo** [comment]
Hi, YES valid Point 😄.

Then we need to change the code to not dismiss the source right at the beginning and store the name and add check to the orphaned logic.

Then you actually need to delete the config from the config file to actually get rid of all the associated objects.

BTW: THANK YOU for all this testing/input/PRs. Highly appreciated 👍

**Comment by gstorme** [comment]
Or maybe work with a per-source config parameter _orphaning_enabled_, and execute the `inventory.tag_all_the_things` with or without the orphaned logic, based on its value.

This way you can leave the source in the configuration and it wouldn't matter if it's enabled|disabled, as long as you set the _orphaning_enabled_ to false.
The orphaning logic will only be skipped when you explicitly set it to false, or if the source is no longer present in the configuration.

This would allow for separate - source specific - runs of the sync, for example every x hours for sources a/b, and every x days for sources x/y.

**daily run**
```
source/a
enabled = true
orphaning_enabled = true

source/b
enabled = true
orphaning_enabled = true

source/x
enabled = false
orphaning_enabled = false

source/y
enabled = false
orphaning_enabled = false
```

**weekly run**
```
source/a
enabled = false
orphaning_enabled = false

source/b
enabled = false
orphaning_enabled = false

source/x
enabled = true
orphaning_enabled = true

source/y
enabled = true
orphaning_enabled = true
```

**Comment by bb-Ricardo** [comment]
That would not work afaik. It checks for all objects with the main tag. And if any object has not been seen during the sync (no matter from which source it came) it will be tagged orphaned.

**Comment by gstorme** [comment]
For now (to be able to continue testing with only some sources enabled) I've done a dirty quick fix by adding a parameter _orphaning_enabled_ under the [netbox] section, and by duplicating the `inventory.tag_all_the_things`. One that does the orphaned tagging, and one that doesn't, and then this:

```
    if bool(config_handler.getboolean("netbox", "orphaning_enabled")) is False:
        log.info("Orphaning disabled, tagging without orphaned logic")
        inventory.tag_all_the_things(nb_handler)

    else:
        log.info("Orphaning enabled, tagging with orphaned logic")
        inventory.tag_orphaned(nb_handler)
```

Don't know yet how to implement this logic on a per-source level to do it properly

**Comment by bb-Ricardo** [comment]
Can you test the latest commit and see if this fixes it for you?

**Comment by gstorme** [comment]
GREAT 😄 
Thanks!!

**Comment by gstorme** [comment]
I had pruning disabled, I only notice now that when pruning is enabled, this is still performed for objects that are not a part of the currently enabled source(s).
Would be good/expected to extend this logic to the pruning as well, so it does not touch objects from disabled sources during this phase?

**Comment by bb-Ricardo** [comment]
Haha, yes, very good point.

Sorry for this sloppy implementation and thank you for the free testing.

This should be quite easy to solve. Hope to find some time the next two days.

**Comment by bb-Ricardo** [comment]
should be fixed with latest commit

**Comment by gstorme** [comment]
👍
