### ISSUE TITLE
Please consider publishing to PyPI

### ISSUE THREAD

**Issue by jeffgdotorg** [bb-Ricardo/netbox-sync#396]
Hi, I'm a product manager at NetBox Labs currently on a mission to identify plugins that ought to appear in [our plugin catalog](https://netboxlabs.com/netbox-plugins/). I would love to include this one, but first it will need to be published to PyPI.

I see there's a PyPI package name collision, which might be what has stopped you publishing it there previously. I'm in communication with the maintainer of the PyPI package currently using the `netbox-sync` name and can put you in touch if that will help.

**Comment by bb-Ricardo** [comment]
Hi @jeffgdotorg,

thank you for considering this tool for the NetBox plugin catalog.

Does it matter netbox-sync is not an actual NetBox plugin? -> https://github.com/bb-Ricardo/netbox-sync/issues/115

I never actually considered to publish this tool on PyPI, but could add it as well

**Comment by jeffgdotorg** [comment]
I overlooked that little detail 🤣

At the moment we don't have a durable way to list non-plugin integrations in the catalog, so adding this project will have to wait. Any time you want to revisit, feel free to reach out on NetDev Slack.

**Comment by bb-Ricardo** [comment]
All good, let me know once their is a 3rd party integrations page (or something like that).

Have a good day
