### ISSUE TITLE
Device platform relation missing (?)

### ISSUE THREAD

**Issue by lucafabbri365** [bb-Ricardo/netbox-sync#408]
Hello,
I'm using NetBox-Sync to sync VMware with NetBox.
The _vm_platform_relation_ parameter is employed to map the VMware platform name to my own platform name (defined in NetBox).
This option works fine for platforms associated with VMs, but it doesn't work for platforms associated with devices (VMware hosts).

Example (_settings.yaml_)

```
...
vm_platform_relation: Red Hat Enterprise Linux 8.* = Red Hat Enterprise Linux 8, VMware ESXi 7.* = VMware ESXi 7.0 Update 3o, VMware ESXi 8.* = VMware ESXi 8.0 Update 2b
...
```
Mapping between **Red Hat Enterprise Linux 8 (64-bit)** (from VMware) and **Red Hat Enterprise Linux 8** (NetBox) is working fine; however mapping between **VMware ESXi 7.0.3** (from VMware) and **VMware ESXi 7.0 Update 3o** (NetBox) is not working, as well as **VMware ESXi 8.0.2** (from VMware) and **VMware ESXi 8.0 Update 2b** (NetBox): it creates two platforms VMware ESXi 7.0.3 and VMware ESXi 8.0.2.

What am I doing wrong?

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for this report. I think you're not doing anything wrong. This relation is just missing.

will add this one as well

**Comment by bb-Ricardo** [comment]
Hi, just added it to the `development` branch. Would you be able to test it out? the new config option is called `host_platform_relation`

Thank you

**Comment by lucafabbri365** [comment]
Hello @bb-Ricardo,
tested and worked fine !!!

May I continue using the version from development branch ?

Thank you.

**Comment by bb-Ricardo** [comment]
That is up to you. You can use dev branch for now. I usually try to keep it clean.

Hope to merge this soon to main.
