### ISSUE TITLE
Netbox sites with comma in name not parsed correctly in site relation mappings

### ISSUE THREAD

**Issue by justinhippen** [bb-Ricardo/netbox-sync#42]
Our Netbox sites are in a "City, State" or "City, Country" format (ex. Chicago, IL or London, UK) and the cluster site relation function would split at the comma causing errors.

I don't know if it is the cleanest, but I fixed this locally with this regex and a slight modification to the strip functions in the vmware/connection.py @ line 190:

`            for relation in re.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)",config_settings.get(relation_option)):`

                object_name = relation.split("=")[0].strip(' "')
                relation_name = relation.split("=")[1].strip(' "')`

**Comment by bb-Ricardo** [comment]
Hi,

that is totally true, site names which contain a comma won't work with this setup.

Your approach sounds great. I will check it out next week.

**Comment by bb-Ricardo** [comment]
Hey,

I found a different regex which works with quoted and unquoted names.
Can you try the "development" branch and see if it works for you?

Thank you

**Comment by justinhippen** [comment]
I was finally able to test the dev branch & everything worked correctly for quoted names.

**Comment by bb-Ricardo** [comment]
Great. Thank you for testing it.
