### ISSUE TITLE
Required custom field with default value

### ISSUE THREAD

**Issue by Azmodeszer** [bb-Ricardo/netbox-sync#423]
NetBox: v4.1.6
Sync: v1.7.0
vSphere: v8.0.3.00000

The sync is trying to create new VMs, but running into an error:

```
2024-11-12 06:03:57,949 - ERROR: NetBox returned: POST /api/virtualization/virtual-machines/ Bad Request
2024-11-12 06:03:57,949 - ERROR: NetBox returned body: {'__all__': ["Missing required custom field 'Icinga2_Monitoring_VM'."]}
```

And yes, this is a required field for VMs. However, it has a default value set, so I'm not sure why it's complaining about a missing field? Does the sync not work with default values?

I've set the field back to optional for now and the error disappears, but would of course prefer having it automatically set for VMs.

**Comment by bb-Ricardo** [comment]
Hi,

reading the documentation (https://netboxlabs.com/docs/netbox/en/stable/customization/custom-fields/) gives the impression the default value is only used in the UI. But when submitting data via API the field is `required`! If the VM has the attribute not assigned in vCenter then netbox-sync can't assign it.

**Comment by Azmodeszer** [comment]
Yeah, I suspected as much. That's too bad. Any functionality, existing or planned, that might allow the sync to have default values set for certain fields via the settings.ini?

**Comment by lukify85** [comment]
Wow, so am I understanding you correctly that creating a non-required Custom Field in NetBox makes API entries for, say, a given IP address with a custom field require a value for it for any POST/PATCH regardless? That's seems like a really unfortunate oversight.

> Hi,
> 
> reading the documentation (https://netboxlabs.com/docs/netbox/en/stable/customization/custom-fields/) gives the impression the default value is only used in the UI. But when submitting data via API the field is `required`! If the VM has the attribute not assigned in vCenter then netbox-sync can't assign it.

**Comment by bb-Ricardo** [comment]
Hi,

There is currently nothing planned. Even though it seems simple to add a default for each option.

The next request from someone else would then be to make filters based on the VM name to apply different defaults accordingly.

I just try to minimize the feature creep.

**Comment by Azmodeszer** [comment]
Alright, fair nuff.

**Comment by bb-Ricardo** [comment]
thank you
