### ISSUE TITLE
Do not change hosts in netbox if they were add manually

### ISSUE THREAD

**Issue by inetman** [bb-Ricardo/netbox-sync#44]
Hi

We have issue when couple hosts with correct domain name already exist in netbox. They already have physical interfaces but when netbox-sync was running it modified their physical interfaces list in netbox.

For example, our case looks like:

1. we add manually host in netbox with physical interfaces (serial number, device-type, etc...)
2. we connected host to switches inside netbox
3. we exported communation matrix from netbox
4. we connected host to switches inside our datacenter based netbox information which was exported in step 3

As you can see this case can exist if somebody use netbox to store commutation matrix (cables) inside netbox. So it is very lovely case because netbox is point of truth for all cables inside your data center.
But after script was running it broke up our truth and created physical interfaces in netbox. Be noticed, that vmk-interfaces should be sync. 

What do you think about it ?

**Comment by bb-Ricardo** [comment]
Hi,

I'm aware of this behavior.

Mostly people would want to automate the data retrieval.

The script usually does not create new interfaces if existing interfaces were found.

Did you read the description of how the data is parsed?

In your case it would be sufficient if the interfaces have their correct MAC address assigned.

Was this tha case?

**Comment by inetman** [comment]
Yes, I read ) But I can't find way to assigne MAC to interface. The interface names is different from how they display in vCenter, for example, if inside vCenter interface named like "vmnic1", then in netbox we already have interface named like "ETH1". Also interface name is based on operation system of host. For example, it has redhat then interface could have name ens192 (for example). 

I think it is correct way because after network adapter firmware upgrade on esxi-host interfaces could be renamed. I thought...

anyway, I think that physical interfaces of host must be defined BEFORE server will install in rack independed of operation system (vmnic1 or ens192). It is best way for commutate team which locate inside datacenter.

**Comment by bb-Ricardo** [comment]
The snyced hosts are always VMWare hosts. The interface names are always the VMWare terminology.

Hope you made a backup before syncing the forst time. You could restore it and add the MAC addresses to the interfaces. Just edit each interface of each host and assign the corresponding MAC address. Then the sync should work as you expect it.

Or just exclude all hosts from syncing. Then this won't happen again.

**Comment by bb-Ricardo** [comment]
any updates?

**Comment by bb-Ricardo** [comment]
Closing this issue due to no response. Please reopen if desired.
