### ISSUE TITLE
FR: Add possibility to map platform

### ISSUE THREAD

**Issue by david-sieg** [bb-Ricardo/netbox-sync#47]
Hi Ricardo,

It would be nice to filter or map vms with defined platform.
We also want to support you in development, if you want.

Best regards,
David

**Comment by bb-Ricardo** [comment]
Hi David,

Do you mean something similar to `host_site_relation` but `vm_platform_relation`? That you have a list of regex matches which assign a predefined platform to matching VMs?

> We also want to support you in development, if you want.

Sounds great 😊, what do you have in mind?

The change should be pretty straight forward.
- Add config option to sample config
- Add this to the vmware source valid config options
- Add to list of validated relations in config validation 
- Add match in `add_vm` to apply relation if set and fall back to current assignment of platform to VM.

**Comment by david-sieg** [comment]
Hi Ricardo,

you are right, similar to host_site_relation.
My collegue will try to change in code. If he will finish, we would like to push in extra branch.

David

**Comment by bb-Ricardo** [comment]
Sounds great.

**Comment by david-sieg** [comment]
Hi Ricardo,

there are several questions, my colleque opened a pull request, maybe u can help him?

David

**Comment by bb-Ricardo** [comment]
Hi, sorry for the late reply. I have seen it but need to change a few things around.

Thank your for the contribution and hopefully will be able to add it soon.

**Comment by vegantofuboy** [comment]
Hi Ricardo,

thanks for your answer. We got already another version of the connection.py we're testing with more changes, but it isn't finish yet. When you want I will open an extra pull request with our new file, but I guess it doesn't make much sense.

I'm really excited to see your solution. 

Thanks for your help :)

Flo

**Comment by bb-Ricardo** [comment]
This sounds like a challange 😀. I'm in. Will try to give it a go this afternoon.

**Comment by bb-Ricardo** [comment]
Hi,

can you check out the branch "feature/add_vm_platform_relation"? -> https://github.com/bb-Ricardo/netbox-sync/tree/feature/add_vm_platform_relation

Thank you

**Comment by vegantofuboy** [comment]
Hi Ricardo,
I tested it. Your split solution is much smarter than we're had :) thanks... but maybe something is wrong at the variable declaration at the line 1942 of the connection.py file.

 ```
platform = None
        for platform_relation in grab(self, "vm_platform_relation", fallback=list()):
            object_regex = platform_relation.get("object_regex")
            print(name) ### this is the servername
            print(object_regex) ### thats the platform name
            if object_regex.match(name): ### the match tries to compare the vm name with the platform?
                platform = platform_relation.get("platform_name")
                log.debug2(f"Found a match ({object_regex.pattern}) for {name}, using platform '{platform}'")
                break
```

I'm not so much into like you but I see that the  If-Condition  not fulfilled and change the platform variable.
Is that correct?

Have a nice weekend so far
Flo

**Comment by bb-Ricardo** [comment]
Hey,

Yes it tries to compare the VM name if it matches the regex expression. Wasn't this your intention?

If not what did you try to do and can you give some more precise examples?

**Comment by vegantofuboy** [comment]
Hi Ricardo,

the buildin VMWare Platform declaration for Windows is "Microsoft Windows Server 2016 or later (64-bit)" or for CentOS is "CentOS 8 (64-bit)". In our environment we change the platform of Windows  to "windows2016" and centos to "centos8" because we want to use shorter platform-names. Now we thought we use the vm_platform_relation like 

`vm_platform_relation = microsoft-windows-server-2016-or-later-64-bit.* = windows2016, centos-8-64-bit.* = centos8`

I guess the compare should go against` platform = get_string_or_none(grab(obj, "guest.guestFullName", fallback=platform))` not the Name of the VMs 

something like

```
platform = get_string_or_none(grab(obj, "guest.guestFullName", fallback=platform))
        for platform_relation in grab(self, "vm_platform_relation", fallback=list()):
            object_regex = platform_relation.get("object_regex")
            if object_regex.match(platform):
                platform = platform_relation.get("platform")
                log.debug2(f"Found a match ({object_regex.pattern}) for {name}, using platform '{platform}'")
                break
```
![grafik](https://user-images.githubusercontent.com/64468897/109389435-dd0b3600-790c-11eb-9470-881fdf666d12.png)

I hope that make sense :) 

Best
Flo

**Comment by bb-Ricardo** [comment]
Changed it around. Does this work for you?

**Comment by vegantofuboy** [comment]
Hi Ricardo,

YES :) that’s it. I tested it and it looks fine so far. 

Thanks for your help Ricardo nice work!
Flo

**Comment by bb-Ricardo** [comment]
Great thank you for testing. Merge to dev branch
