### ISSUE TITLE
Way to not overwrite device name after changing device name in netbox

### ISSUE THREAD

**Issue by jozefrebjak** [bb-Ricardo/netbox-sync#55]
Hello, 

Is there a way how to not overwrite the device name after changing the name in netbox after successfully added the device? 

Let's explain. We have ESXi hosts added to vCenter only with IP addresses, because of not carrying about DNS from past days. Now we have a DNS record for every ESXi host, but we don't want to change hosts in clusters, because it's not so easy.

So I would like to change the name in Netbox, which will be for us fine, because of the easiest way to find the device, but when I did it, then with the new cron job of sync device names were changed back to IP Address. Will be nice to have an option to not overwrite the device name within cron job, when the device is already found and added on first run. 

@bb-Ricardo what you think? 

Thank you.

**Comment by bb-Ricardo** [comment]
hi,

I guess this would be possible but then it would cause issues with objects which can only be associated via their name.
