### ISSUE TITLE
PR: add vm_role_relation

### ISSUE THREAD

**Issue by david-sieg** [bb-Ricardo/netbox-sync#56]
Hi Ricardo,

it would be nice to have an extra option to map vms to specific roles.
Same like #vm_tenant_relation = grafana.* = Infrastructure.

Should also be:

#Map vms to specified roles
#vm_role_relation = grafana.* = Grafana_role

Best regards,
David

**Comment by bb-Ricardo** [comment]
Added this FR to the current "development" branch. Can you check it out and test it please?

**Comment by david-sieg** [comment]
Hi Ricardo,

vm_role_relation runs fine, thx!

David
