### ISSUE TITLE
Adding a new ip prefix in settings.ini, netbox v2.11

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#59]
Hi!
Thanks for your work!
After update scrip a new version add support netbox 2.11 (https://github.com/bb-Ricardo/netbox-sync/issues/58)
I have a new problem, when i add new prefix (my public prefix) in config file and start script, he return the error. 
How, i may fix it ?

> 
> 2021-04-26 12:36:38,712 - WARNING: IP prefix length of '172.16.184.74/29' (vNIC 1 (vDS Vlan184 172.16.184.0) (aso-cod-01)) does not match network prefix length '172.16.184.0/24'!
> Traceback (most recent call last):
>   File "./netbox-sync.py", line 143, in <module>
>     main()
>   File "./netbox-sync.py", line 119, in main
>     source.apply()
>   File "/opt/scripts/netbox-sync/module/sources/vmware/connection.py", line 373, in apply
>     view_details.get("view_handler")(obj)
>   File "/opt/scripts/netbox-sync/module/sources/vmware/connection.py", line 2170, in add_virtual_machine
>     self.add_device_vm_to_inventory(NBVM, object_data=vm_data, site_name=site_name, vnic_data=nic_data,
>   File "/opt/scripts/netbox-sync/module/sources/vmware/connection.py", line 989, in add_device_vm_to_inventory
>     device_vm_object = self.inventory.add_object(object_type, data=object_data, source=self)
>   File "/opt/scripts/netbox-sync/module/netbox/inventory.py", line 153, in add_object
>     new_object = object_type(data, read_from_netbox=read_from_netbox, inventory=self, source=source)
>   File "/opt/scripts/netbox-sync/module/netbox/object_classes.py", line 96, in __init__
>     self.update(data=data, read_from_netbox=read_from_netbox, source=source)
>   File "/opt/scripts/netbox-sync/module/netbox/object_classes.py", line 375, in update
>     float(current_value) == float(new_value):
> TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by Sivolen** [comment]
I'm temporary fixed it but i don't understand that wrong in my netbox 
```

            try:
                if self.data_model.get(key) in [int, float] and isinstance(new_value, (int, float)) and \
                        float(current_value) == float(new_value):

                    continue
            except Exception as e:
                print(e)
```

Result 

> 
> 2021-04-26 14:43:21,067 - WARNING: IP prefix length of '172.16.184.74/29' (vNIC 1 (vDS Vlan184 172.16.184.0) (aso-cod-01)) does not match network prefix length '172.16.184.0/24'!
> float() argument must be a string or a number, not 'NoneType'
> float() argument must be a string or a number, not 'NoneType'
> float() argument must be a string or a number, not 'NoneType'
> float() argument must be a string or a number, not 'NoneType'

**Comment by bb-Ricardo** [comment]
Hi,

The latest commit should resolve the issue. Can you test it please?

**Comment by Sivolen** [comment]
Hi!
I tested this code, it works correctly, thanks!
