### ISSUE TITLE
Server creation problem

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#68]
![image](https://user-images.githubusercontent.com/36307887/119978241-10b83380-bfc2-11eb-9697-3935485bad00.png)
Added one server to vcenter today, added it to settings. After synchronization, it was added to netbox but merged with another server, that is, the name is correct and it took the interfaces from another server. I tried removing it but on next sync it merges with another server.

**Comment by SerhiiZahuba** [comment]
on the screenshot you can see
my new server is 192.168.50.145 but he took the interfaces from another server

**Comment by bb-Ricardo** [comment]
Can you correct it in NetBox again and then do another run with DEBUG2 debug level and provide the log. There must be something going where it matches the other server as well.

Thank you.

**Comment by SerhiiZahuba** [comment]
[netbox_sync.log](https://github.com/bb-Ricardo/netbox-sync/files/6561392/netbox_sync.log)
![image](https://user-images.githubusercontent.com/36307887/119997134-13258800-bfd8-11eb-8927-5a6ba1d454f1.png)


for example, I deleted the server 192.168.50.170, I start the synchronization and it did not create it back, also on the screen to the server 192.168.49.25 IP addresses from another site were added, the log was attached

**Comment by SerhiiZahuba** [comment]
I would like to delete the log, please write when you download it to yourself

**Comment by bb-Ricardo** [comment]
done. Sorry for the delay.

**Comment by SerhiiZahuba** [comment]
![image](https://user-images.githubusercontent.com/36307887/120060634-83c4b700-c061-11eb-90ae-458c14d9bfab.png)
![image](https://user-images.githubusercontent.com/36307887/120060644-92ab6980-c061-11eb-9d0d-d5107b696784.png)
one more note, I returned the old backup (for April), in settings.ini I did not add my new host, after synchronization it was added (see the screen) to the default site, but it took the IP addresses from another host

**Comment by bb-Ricardo** [comment]
Hi, Had a look and it seems to have something to do with serial numbers / asset tags.

can you check if "10.250.1.100" and "192.168.49.25" have the same serial number? 123456789?

**Comment by SerhiiZahuba** [comment]
Hello. Yes, the serial numbers are the same.

**Comment by bb-Ricardo** [comment]
Well, this is the issue. A Serial number is meant to be unique (https://en.wikipedia.org/wiki/Serial_number). The script finds a device with the same serial and assumes it is the matching object. And If you have even more then two devices with the same serial then it even get's worse.

can you set the serial manually or why is it "123456789"?

**Comment by SerhiiZahuba** [comment]
Yes, I will try to change this parameter. New supermicro servers arrived with this parameter - and it's very strange. If this is not very difficult for you, can you add a parameter to the script that will not merge servers with the same serial numbers?

**Comment by bb-Ricardo** [comment]
Hi,

You can just try it out yourself. Just comment out this line and run it again.

https://github.com/bb-Ricardo/netbox-sync/blob/95d285309ab78f8bbc9758b780bd1a0a4677a8e5/module/sources/vmware/connection.py#L966

Does this work better?

**Comment by bb-Ricardo** [comment]
Hi. Was wondering if there is any update on that? Or can I close this issue?

**Comment by bb-Ricardo** [comment]
Hey, can you check out the current release?

There is a new config option:
https://github.com/bb-Ricardo/netbox-sync/blob/1337df6139129685c0a0a5c3ffad3defbfd26ddd/settings-example.ini#L181-L183

**Comment by SerhiiZahuba** [comment]
Thank you I saw. You are the best as always)) Last time I added my server manually and there were no problems with synchronization.
