### ISSUE TITLE
I have a question for VM interface description

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#69]
Hi!
I delete VM in vmware. 
After that the script removes it from netbox but if the ip address on interface VM have description  the script cannot delete this ip.
How i may fix it ?

**Comment by bb-Ricardo** [comment]
Hi,

So if you add a description to the IP address in NetBox then the script can't delete the IP?

**Comment by Sivolen** [comment]
Hi, yes

**Comment by bb-Ricardo** [comment]
Then there should be an error message in the netbox_sync.log. Can you have a look?

**Comment by bb-Ricardo** [comment]
Hi. Was wondering if there is any update on that? Or can I close this issue?

**Comment by Sivolen** [comment]
Hi!
It's my mistake, skript work well .
