### ISSUE TITLE
Sync VM Templates even when skip_vm_templates = true

### ISSUE THREAD

**Issue by AustinM731** [bb-Ricardo/netbox-sync#77]
The initial sync to Netbox will exclude the Templates, but any subsequent sync will sync the VM Templates.

**Comment by AustinM731** [comment]
Updating to the latest version of Netbox was able to resolve this issue.

**Comment by bb-Ricardo** [comment]
That was an easy fix 😬

**Comment by AustinM731** [comment]
Yea, it was really weird since the initial sync would work as intended. But every subsequent sync would grab all of my templates.
