### ISSUE TITLE
Two vSphere on one site

### ISSUE THREAD

**Issue by Sivolen** [bb-Ricardo/netbox-sync#78]
I have two vSphere on one site, after run script i saw next message:

`ERROR: Problem while config file parsing: While reading from '/opt/scripts/netbox-sync/settings.ini' [line 231]: section 'source/DC-SRG' already exists`

May i can use script with two vSphere on one  site?

**Comment by bb-Ricardo** [comment]
Hi, you have to simply give it a different name as it is a different vCenter.

`[source/DC-SRG2]` for example

**Comment by Sivolen** [comment]
Hi!
I thought about it, but the script will create a new site (DC-SRG2). 
Second vSphere has the same site as the first and the servers are located there too

**Comment by bb-Ricardo** [comment]
Hi,

you need to use and set this option:
https://github.com/bb-Ricardo/netbox-sync/blob/1337df6139129685c0a0a5c3ffad3defbfd26ddd/settings-example.ini#L145-L153

**Comment by Sivolen** [comment]
Hi It's great )) Thanks
