### ISSUE TITLE
"ERROR: (vmodl.fault.NotSupported)"

### ISSUE THREAD

**Issue by nathan-sav** [bb-Ricardo/netbox-sync#8]
This might not be a legitimate error, but it's showing up in the debug logs so just wanted to flag it for your attention.

The context around it doesn't seem to indicate what exactly is failing here, so I think this might just be a bulk request from vmware that includes a not supported sub-object?

```
   (vim.alarm.AlarmState) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 'alarm-9.vm-6505',
      entity = 'vim.VirtualMachine:vm-6505',
      alarm = 'vim.alarm.Alarm:alarm-9',
      overallStatus = 'gray',
      time = 2020-11-16T17:59:09.186577Z,
      acknowledged = false,
      acknowledgedByUser = <unset>,
      acknowledgedTime = <unset>,
      eventKey = <unset>
   }
]2020-11-20 00:43:59,866 - ERROR: (vmodl.fault.NotSupported) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = '',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

send: b'POST /sdk HTTP/1.1\r\nHost: 10.32.0.200\r\nContent-Length: 682\r\nCookie: vmware_soap_session="196f12d4851c9682469ed280e"; Path=/; HttpOnly; Secure;\r\nSOAPAction: "urn:vim25/6.7.3"\r\nContent-Type: text/xml; charset=UTF-8\r\nUser-Agent: pyvmomi Python/3.8.5 (Linux; 5.4.0-47-generic; x86_64)\r\nAccept-Encoding: gzip, deflate\r\n\r\n'
send: b'<?xml version="1.0" encoding="UTF-8"?>\n<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">\n<soapenv:Body><RetrievePropertiesEx xmlns="urn:vim25"><_this type="PropertyCollector">property>reply: 'HTTP/1.1 200 OK\r\n'
```

This happens 4 times during each sync

**Comment by bb-Ricardo** [comment]
are you using vCenter 7.0 ?

I don't have an instance where I could test this. Thsi might also be the same issue with tha "/" in the portgroup name.

you could just remove the version information from 'pyvmomi' in `requirements.txt` and update your environment. Newest version of pyvmomi sould be 7.0.1.

Can you try this and then run teh sync again?

Thank you

**Comment by nathan-sav** [comment]
Ah yeah, I'm on the absolutely latest 7.0u1. Issue still persists with the latest pyvmomi.

Here's the full log of the request the failure seems to be associated with:
[vmodlfault.txt](https://github.com/bb-Ricardo/netbox-sync/files/5575531/vmodlfault.txt)

**Comment by bb-Ricardo** [comment]
This sure looks very much like a pyvmomi issue

**Comment by nathan-sav** [comment]
Agreed. I'm cool with this being closed, I'm not seeing any impact to the tool from it.
