### ISSUE TITLE
Add WARNING if no usable IP addresses for host or VM were found

### ISSUE THREAD

**Issue by AxisNL** [bb-Ricardo/netbox-sync#81]
Hi, thank you so much for what you're doing for us with this project! It's a life saver. Small ngo though, and almost no funds, otherwise I'd pay you for your time.

We have some ESX hosts (rented bare metal servers all over the internet) where we're doing ipv6 only. Saves money on the ipv4 addresses ;)

netbox-sync doesn't seem to be able to cope with ipv6 addresses though:

ERROR: IP address '/' for vmk0 invalid!

IPv6 support would be awesome!

**Comment by bb-Ricardo** [comment]
Hey, really glad to help an NGO with this project.

IPv6 should be supported. At least that's what I try to build in.

Would you mind to run the script with `-l DEBUG2` and send me the complete output of the first host where this problem occurs?

Thank you.

**Comment by AxisNL** [comment]
Doh! 'IP address '2a00:7c80:xxx/64' for vmk0 not part of any permitted subnet. Skipping.'.. Makes sense ;)

**Comment by AxisNL** [comment]
Adding 2000::/3 to the permitted_subnets fixed that. IPv6 works perfectly!

The error message "ERROR: IP address '/' for vmk0 invalid!" is because the nic does not have ipv4 enabled.

**Comment by bb-Ricardo** [comment]
A WARNING should be added if no IP addresses where found!
