### ISSUE TITLE
Allow matching a vmware device to an existing device via serial number / asset tag

### ISSUE THREAD

**Issue by nathan-sav** [bb-Ricardo/netbox-sync#9]
I have all my servers in netbox already, but when running sync it's created new devices for each of my esxi hosts using the vmware IP. I could just merge the two together, but down the road there's a high probability that I'm going to reprovision the same hardware and move it from one vmware cluster to another.

Ideally it'd be possible to discover a vmware host already exists in netbox just by matching the serial number (on my systems this is the dell service tag), this way netbox-sync would just move it over to the correct location when the host is reprovisioned. 

There's probably complications here I'm not thinking about though, like how to deal with all the interfaces and their physical connections (can't just delete anything not matching, would have to update based on the vmnic# name probably?)

**Comment by bb-Ricardo** [comment]
Hi Nathan, thanks for all the testing.

I thought about this option as well. I'm also not sure if this will work properly. I woll create a branch with this option and let you know about it. You could and see if it works.

Also helpfull to run the program with the `-n` option to see what will happen without writing the data to netbox.

**Comment by bb-Ricardo** [comment]
please try this branch and see if it works. Please also test, if possible, moving a host to a differnt cluster to check what actually will happen.

Will probably also cause problems if host moves sites as assigned IP address would prevent moving the host in NetBox.

**Comment by nathan-sav** [comment]
Not working, looks like serial and asset_tag aren't the right properties:

```
2020-11-20 19:05:04,977 - DEBUG2: Trying to find a device based on the collected name, cluster, IP and MAC addresses
2020-11-20 19:05:04,980 - DEBUG2: No exact match found. Trying to find device based on MAC addresses
2020-11-20 19:05:04,983 - DEBUG2: No match found. Trying to find device based on primary IP addresses
2020-11-20 19:05:04,984 - DEBUG: No exiting device object for 10.32.0.101. Creating a new device.
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'device' data structure: 10.32.0.101
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'device role' data structure: Server
2020-11-20 19:05:04,984 - DEBUG: Updated device role object: Server
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'device type' data structure: PowerEdge R6515
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'manufacturer' data structure: Dell Inc.
2020-11-20 19:05:04,984 - DEBUG: Updated manufacturer object: Dell Inc.
2020-11-20 19:05:04,984 - DEBUG: Updated device type object: PowerEdge R6515
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'site' data structure: vCenter: sav
2020-11-20 19:05:04,984 - DEBUG: Updated site object: vCenter: sav
2020-11-20 19:05:04,984 - DEBUG2: Parsing 'cluster' data structure: SAV-V1A
2020-11-20 19:05:04,984 - DEBUG: Updated cluster object: SAV-V1A
2020-11-20 19:05:04,984 - INFO: Created new device object: 10.32.0.101
```

I believe you need to use one of these (I've swapped my service tag for XXX1234):

```
         (vim.host.SystemIdentificationInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            identifierValue = 'XXX1234',
            identifierType = (vim.ElementDescription) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               label = 'Service tag',
               summary = 'Service tag of the system',
               key = 'ServiceTag'
            }
         },
         (vim.host.SystemIdentificationInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            identifierValue = 'XXX1234',
            identifierType = (vim.ElementDescription) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               label = 'Enclosure serial number tag',
               summary = 'Enclosure serial number tag of the system',
               key = 'EnclosureSerialNumberTag'
            }
         },
         (vim.host.SystemIdentificationInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            identifierValue = 'XXX1234',
            identifierType = (vim.ElementDescription) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               label = 'Serial number tag',
               summary = 'Serial number tag of the system',
               key = 'SerialNumberTag'
            }
         },
```

**Comment by bb-Ricardo** [comment]
Is the serial even synced to NetBox.

Serial and Asset Tag are grabbed from this list from the host object "summary.hardware.otherIdentifyingInfo"

Line #1285 in module.sources.vmware.connection

Maybe the attribute name changed.

Can you have a look at it?

Thank you.

**Comment by nathan-sav** [comment]
Ah, I didn't realize it was supposed to be syncing the serial number already. No, it's not currently doing that. I added some debugging and {serial} is set properly though, so it's not an issue pulling it from vmware. Seems to be a netbox api issue since setting host_data["serial"]: "test" at line 1340 still doesn't put the data into netbox.

**Comment by bb-Ricardo** [comment]
Try changing the line `serial = None` and set it to `test` and try again. This should change the serial. A dry run should show the change already.

**Comment by nathan-sav** [comment]
Nope, still nothing. It's not an issue pulling the serial number from vmware, it's an issue putting it into netbox. The serial variable does get set to the service tag as I expect, it's always blank in netbox even if I hard code serial to test.

**Comment by bb-Ricardo** [comment]
Then i did something wrong there. Will investigate.

And even with DEBUG3 the serial is not included in the host data structure before it starts trying to match the host?

**Comment by nathan-sav** [comment]
I don't think your debug3 command is doing what you expect, it just prints the object pointer rather than a dump of the contents:

```
2020-11-20 20:47:55,437 - DEBUG3: function: add_device_vm_to_inventory
2020-11-20 20:47:55,437 - DEBUG3: Object type <class 'module.netbox.object_classes.NBVM'>
```

If I search the log (on debug3) for the service tag, it's not mentioned anywhere outside of the vmware responses.

**Comment by bb-Ricardo** [comment]
The information I would need is printed to stdout, not to the log file. You should be able to get all the output like this: `./netbox-sync.py -l DEBUG3 > my-debug3.log 2>&1`

**Comment by nathan-sav** [comment]
Ah, that's what I was doing, but I think there's some output buffering going on with either stderr or stdout so things don't match up in the same spots. I found the object further down, I don't see a serial number in it at all.

**Comment by bb-Ricardo** [comment]
Than I know where to look.

Thanks for testing out this one.

**Comment by bb-Ricardo** [comment]
I might have found the issue:

in these lines (1329 to 1334) i used a double colon to assign values but this is wrong. That's a copy & paste error and my IDE thought this is totally cool as well. 🤦 

I just pushed a new commit to this branch. Would you mind testing again?

Thank you

**Comment by bb-Ricardo** [comment]
any chance you could test this?

**Comment by bb-Ricardo** [comment]
Due to no response in over a month I will close the ticket for now.
