### ISSUE TITLE
Possibly a bug? permitted cluster

### ISSUE THREAD

**Issue by SerhiiZahuba** [bb-Ricardo/netbox-sync#90]
After switching to a new release of the script, I see in the log that all VM updates are not applied and in the log I see next to each VM
DEBUG: Virtual machine 'HQ-VS-LNX-FARM-1' is not part of a permitted cluster. Skipping.

I have not changed the settings.ini settings. Help me please.

**Comment by bb-Ricardo** [comment]
Hi, I had a bug in there. Can you pull the latest `main` branch again?

Sorry for this.

**Comment by SerhiiZahuba** [comment]
I think it's okay. I started syncing, then changed the VM and started syncing again - everything is fine. thanks

**Comment by bb-Ricardo** [comment]
great. Will close the ticket
