### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded in comparison" after pulling development branch

### ISSUE THREAD

**Issue by david-sieg** [bb-Ricardo/netbox-sync#92]
Hello Ricardo,

our sync- task is failing because of commit from 09.09.2021, we changed to main branch and task is working again.

Best regards
David

Output from Ansible:

{
    "msg": "non-zero return code",
    "cmd": [
        "./netbox-sync/netbox-sync.py"
    ],
    "stdout": "",
    "stderr": "2021-09-10 20:55:33,372 - INFO: Starting NetBox Sync\n2021-09-10 20:55:33,409 - INFO: Successfully connected to NetBox 'netbox'\nRecursionError: maximum recursion depth exceeded in comparison",
    "rc": 1,
    "start": "2021-09-10 20:55:32.968995",
    "end": "2021-09-10 20:56:18.406161",
    "delta": "0:00:45.437166",
    "changed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "./netbox-sync/netbox-sync.py",
            "warn": true,
            "_uses_shell": false,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "argv": null,
            "chdir": null,
            "executable": null,
            "creates": null,
            "removes": null,
            "stdin": null
        }
    },
    "stdout_lines": [],
    "stderr_lines": [
        "2021-09-10 20:55:33,372 - INFO: Starting NetBox Sync",
        "2021-09-10 20:56:18,248 - INFO: Updating changed data in NetBox",
        "Traceback (most recent call last):",
        "  File \"./netbox-sync/netbox-sync.py\", line 143, in <module>",
        "    main()",
        "  File \"./netbox-sync/netbox-sync.py\", line 133, in main",
        "    nb_handler.update_instance()",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/netbox/connection.py\", line 694, in update_instance",
        "    self.update_object(nb_object_sub_class, unset=True)",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/netbox/connection.py\", line 583, in update_object",
        "    self.update_object(dependency)",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/netbox/connection.py\", line 583, in update_object",
        "    self.update_object(dependency)",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/netbox/connection.py\", line 583, in update_object",
        "    self.update_object(dependency)",
        "  [Previous line repeated 991 more times]",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/netbox/connection.py\", line 582, in update_object",
        "    log.debug2(\"Resolving dependency: %s\" % dependency.name)",
        "  File \"/tmp/awx_46352_b06_q7ty/project/playbooks/netbox/netbox-sync/module/common/logging.py\", line 31, in debug2",
        "    if self.isEnabledFor(DEBUG2):",
        "  File \"/usr/lib64/python3.6/logging/__init__.py\", line 1548, in isEnabledFor",
        "    if self.manager.disable >= level:",
        "RecursionError: maximum recursion depth exceeded in comparison"
    ],
    "_ansible_no_log": false,
    "attempts": 5,
    "_ansible_delegated_vars": {}
}

**Comment by bb-Ricardo** [comment]
Could you try `development-fixed` branch. This should work better.

Any reason you are using development branch?

**Comment by david-sieg** [comment]
Your suggested branch works fine, there is no special reason why I use development branch.
You developed some of my requested features (e.g. vm_tenant_relation) and u also merged into development.
That's my reason why I use dev- branch -> (I never changed ...)

**Comment by bb-Ricardo** [comment]
ahh ok. Will hopefully soon release another release. And will keep the release cycles shorter.

Would recommend to switch to `main`.

**Comment by david-sieg** [comment]
> Would recommend to switch to `main`.

already done... thx

**Comment by bb-Ricardo** [comment]
will close this issue for now
