### ISSUE TITLE
FR: add option for vm_tag_relation

### ISSUE THREAD

**Issue by david-sieg** [bb-Ricardo/netbox-sync#98]
Hi Ricardo,

it would be nice to get another nice feature which will be used to set tags related to vm name.
(same like vm_tenant_relation)

`#host_tag_relation = esxi300.* = Infrastructure
#vm_tag_relation = grafana.* = Infrastructure`

David

**Comment by bb-Ricardo** [comment]
Seems doable

**Comment by bb-Ricardo** [comment]
Hey, can you please checkout this branch https://github.com/bb-Ricardo/netbox-sync/tree/feature/vm_tag_relation and test if it works?

Thank you
