### ISSUE TITLE
ESXi host not get synced

### ISSUE THREAD

**Issue by sincomil** [bb-Ricardo/netbox-sync#99]
When running sync VMs getting imported, but ESXi hosts not.
Attaching log output from running app.

**Comment by bb-Ricardo** [comment]
your issue looks a lot like #79 . I will try fixing this in a more generic way.

you could try the "source-check-redfish" branch and see if it works better with this version.

Sorry for the inconvenience

**Comment by sincomil** [comment]
Thank you for reply. I have tried suggested branch - no luck :(
[complete.log](https://github.com/bb-Ricardo/netbox-sync/files/7258535/complete.log)

**Comment by bb-Ricardo** [comment]
thank you for testing. Can you give `fix/manufacturer-slug-issue` a try?

you should also delete the log files.

**Comment by sincomil** [comment]
Good job, @bb-Ricardo !
Now it works!

**Comment by bb-Ricardo** [comment]
Great. And thank you for testing. This will be added in the next version.

Meanwhile you could just stay on this commit.

You still should delete the two log files you attached here.

**Comment by sincomil** [comment]
Ok. Thank you for you job.

Sorry but I could not figured out how to delete uploaded files here. So I edited a comments and removed links to that files, is it enough?

**Comment by bb-Ricardo** [comment]
I think so. Will close this issue as resolved.
